'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {CalendarDays,ChevronRight,Clock3,FileText,Hourglass,Info,Plus,Upload,X,XCircle} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {formatBytes,validateLeaveFile} from '@/lib/teacher-leave';
import {Balance,Detail,Empty,ErrorState,Header,Shell,Stat,Badge} from './LeaveViews';
type Mode='home'|'apply'|'detail'|'balance';
export type Leave={id:string;leave_type:string;start_date:string;end_date:string;reason:string;status:string;principal_note:string|null;reviewed_by:string|null;reviewed_at:string|null;created_at:string;total_days:number;attachment_path:string|null;attachment_name:string|null;attachment_mime:string|null;attachment_size:number|null;cancelled_at:string|null};
export type LeaveType={id:string;code:string;name:string;allocation_days:number|null};
type Holiday={event_date:string;end_date:string|null};
export type Data={userId:string;teacherId:string;schoolId:string;leaves:Leave[];types:LeaveType[];holidays:Holiday[];weekdays:number[]};
const card='rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950',field='w-full rounded-xl border border-slate-200 bg-transparent px-3 py-2.5 text-sm outline-none focus:border-blue-500 dark:border-slate-700';
export const pretty=(v:string,time=false)=>new Intl.DateTimeFormat('en-US',time?{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kathmandu'}:{month:'short',day:'numeric',year:'numeric'}).format(new Date(v.length===10?v+'T12:00:00':v));
export const typeName=(data:Data,code:string)=>data.types.find(t=>t.code===code)?.name||code.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function TeacherLeave({mode,leaveId}:{mode:Mode;leaveId?:string}){const router=useRouter(),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const {data:auth}=await supabase.auth.getUser();if(!auth.user)throw Error('Please sign in with your teacher account.');const {data:p}=await supabase.from('profiles').select('school_id,role').eq('user_id',auth.user.id).single();if(p?.role!=='teacher'||!p.school_id)throw Error('Teacher access unavailable.');const {data:t}=await supabase.from('teachers').select('id').eq('school_id',p.school_id).eq('user_id',auth.user.id).is('left_at',null).single();if(!t)throw Error('Active teacher membership unavailable.');const [lr,tr,hr,wr]=await Promise.all([supabase.from('teacher_leave_requests').select('id,leave_type,start_date,end_date,reason,status,principal_note,reviewed_by,reviewed_at,created_at,total_days,attachment_path,attachment_name,attachment_mime,attachment_size,cancelled_at').eq('school_id',p.school_id).eq('teacher_id',t.id).order('created_at',{ascending:false}),supabase.from('school_leave_types').select('id,code,name,allocation_days').eq('school_id',p.school_id).eq('active',true).order('name'),supabase.from('news_events').select('event_date,end_date').eq('school_id',p.school_id).eq('is_event',true).eq('category','holiday'),supabase.from('teacher_assignments').select('weekday').eq('school_id',p.school_id).eq('active',true).not('weekday','is',null)]);const issue=lr.error||tr.error||hr.error||wr.error;if(issue)throw issue;setData({userId:auth.user.id,teacherId:t.id,schoolId:p.school_id,leaves:(lr.data||[]) as Leave[],types:(tr.data||[]) as LeaveType[],holidays:(hr.data||[]) as Holiday[],weekdays:Array.from(new Set((wr.data||[]).map(r=>r.weekday as number)))})}catch(reason){setError(reason instanceof Error?reason.message:'Could not load leave requests.')}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 if(loading)return <Shell><div className="mx-auto h-80 max-w-3xl animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800"/></Shell>;if(error||!data)return <Shell><ErrorState message={error} retry={load}/></Shell>;
 const leave=leaveId?data.leaves.find(l=>l.id===leaveId):undefined;if(mode==='detail'&&!leave)return <Shell><ErrorState message="This leave request is unavailable or does not belong to you." retry={()=>router.push('/teacher/leave')}/></Shell>;
 if(mode==='apply')return <Shell><Apply data={data} back={()=>router.back()}/></Shell>;if(mode==='balance')return <Shell><Balance data={data} back={()=>router.back()}/></Shell>;if(mode==='detail')return <Shell><Detail data={data} leave={leave!} back={()=>router.back()} refresh={load}/></Shell>;return <Shell><Home data={data}/></Shell>}
function Home({data}:{data:Data}){const [filter,setFilter]=useState('All');const shown=data.leaves.filter(l=>filter==='All'||l.status===filter.toLowerCase());const used=data.leaves.filter(l=>l.status==='approved').reduce((n,l)=>n+l.total_days,0),pending=data.leaves.filter(l=>l.status==='pending').reduce((n,l)=>n+l.total_days,0),total=data.types.reduce((n,t)=>n+(t.allocation_days||0),0),available=total?Math.max(0,total-used-pending):null;return <div className="mx-auto max-w-3xl space-y-4"><header><h1 className="text-3xl font-extrabold">Leave</h1><p className="text-sm text-slate-500">Apply for leave and track your requests.</p></header><Link href="/teacher/leave/apply" className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 font-semibold text-white"><Plus/>Apply for Leave</Link><div className="grid grid-cols-4 gap-2"><Stat icon={CalendarDays} value={total||'—'} label="Total Days" tone="green"/><Stat icon={Clock3} value={available??'—'} label="Available" tone="blue"/><Stat icon={Hourglass} value={pending} label="Pending" tone="amber"/><Stat icon={XCircle} value={used} label="Used" tone="rose"/></div>{!total&&<Link href="/teacher/leave/balance" className="block rounded-xl bg-blue-50 p-3 text-xs text-blue-700 dark:bg-blue-950/40">Your school has not configured leave allocations. Request history remains available. View balance →</Link>}<div className="grid grid-cols-4 border-b dark:border-slate-800">{['All','Pending','Approved','Rejected'].map(v=><button key={v} onClick={()=>setFilter(v)} className={`border-b-2 py-3 text-sm ${filter===v?'border-blue-600 font-semibold text-blue-600':'border-transparent text-slate-500'}`}>{v}</button>)}</div><div className={`${card} divide-y dark:divide-slate-800`}>{shown.map((l,i)=><Link href={`/teacher/leave/${l.id}`} key={l.id} className="grid grid-cols-[48px_1fr_auto] items-center gap-3 p-3"><span className={`grid h-12 w-12 place-items-center rounded-xl ${['bg-emerald-50 text-emerald-600','bg-violet-50 text-violet-600','bg-amber-50 text-amber-600','bg-blue-50 text-blue-600'][i%4]}`}><CalendarDays/></span><div><b>{typeName(data,l.leave_type)}</b><p className="text-xs text-slate-500">{pretty(l.start_date)}{l.end_date!==l.start_date?` – ${pretty(l.end_date)}`:''}</p><span className="text-xs text-slate-500">{l.total_days} day{l.total_days===1?'':'s'}</span></div><div className="flex items-center gap-1"><Badge status={l.status}/><ChevronRight className="h-4 w-4"/></div></Link>)}</div>{!shown.length&&<Empty/>}<Link href="/teacher/leave/balance" className="block text-center text-sm font-semibold text-blue-600">View Leave Balance</Link></div>}
function workingDays(data:Data,start:string,end:string){if(!start||!end||end<start)return 0;let count=0;for(let d=new Date(start+'T12:00:00'),last=new Date(end+'T12:00:00');d<=last;d.setDate(d.getDate()+1)){const iso=d.toISOString().slice(0,10),holiday=data.holidays.some(h=>iso>=h.event_date&&iso<=(h.end_date||h.event_date));if(!holiday&&(!data.weekdays.length||data.weekdays.includes(d.getDay())))count++}return Math.max(1,count)}
function Apply({data,back}:{data:Data;back:()=>void}){const router=useRouter(),[type,setType]=useState(data.types[0]?.code||''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[reason,setReason]=useState(''),[file,setFile]=useState<File|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);const days=workingDays(data,start,end);
 function choose(f:File|null){if(!f){setFile(null);return}const issue=validateLeaveFile(f);if(issue){setError(issue);return}setError('');setFile(f)}
 async function submit(){if(!type||!start||!end||end<start||reason.trim().length<5){setError('Select a leave type, valid dates, and provide at least 5 characters for the reason.');return}setSaving(true);setError('');let path='';try{if(file){const ext=file.name.split('.').pop()?.toLowerCase()||'file';path=`${data.schoolId}/${data.userId}/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from('teacher-leave').upload(path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error}const result=await supabase.from('teacher_leave_requests').insert({school_id:data.schoolId,teacher_id:data.teacherId,leave_type:type,start_date:start,end_date:end,reason:reason.trim(),status:'pending',attachment_path:path||null,attachment_name:file?.name||null,attachment_mime:file?.type||null,attachment_size:file?.size||null});if(result.error)throw result.error;router.push('/teacher/leave')}catch(reason){if(path)await supabase.storage.from('teacher-leave').remove([path]);setError(reason instanceof Error?reason.message:'Could not submit request.')}finally{setSaving(false)}}
 return <div className="mx-auto max-w-2xl space-y-4"><Header back={back} title="Apply for Leave"/>{data.types.length?<><section className={`${card} space-y-4 p-4`}><label className="block text-sm font-semibold">Leave Type *<select value={type} onChange={e=>setType(e.target.value)} className={`${field} mt-1`}>{data.types.map(t=><option key={t.id} value={t.code}>{t.name}{t.allocation_days===null?'':` · ${t.allocation_days} days`}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-sm">Start date *<input type="date" value={start} onChange={e=>{setStart(e.target.value);if(!end||end<e.target.value)setEnd(e.target.value)}} className={`${field} mt-1`}/></label><label className="text-sm">End date *<input type="date" min={start} value={end} onChange={e=>setEnd(e.target.value)} className={`${field} mt-1`}/></label></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-900">Total working days <b className="float-right">{days}</b></div><label className="block text-sm">Reason *<textarea value={reason} onChange={e=>setReason(e.target.value.slice(0,1000))} rows={5} className={`${field} mt-1`} placeholder="Please provide a detailed reason…"/><span className="float-right text-xs text-slate-400">{reason.length}/1000</span></label><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-blue-50 p-3 font-semibold text-blue-600 dark:bg-blue-950/40"><Upload/>Upload File<input className="hidden" type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png,.webp" onChange={e=>choose(e.target.files?.[0]||null)}/></label>{file&&<div className="flex items-center gap-2 rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><FileText/><span className="min-w-0 flex-1 truncate text-sm">{file.name}<small className="block">{formatBytes(file.size)}</small></span><button onClick={()=>setFile(null)}><X/></button></div>}{error&&<p className="text-sm text-red-600">{error}</p>}</section><div className="grid grid-cols-2 gap-3"><button onClick={back} className="rounded-xl bg-slate-100 py-3 font-semibold dark:bg-slate-800">Cancel</button><button onClick={submit} disabled={saving} className="rounded-xl bg-blue-600 py-3 font-semibold text-white">{saving?'Submitting…':'Submit Request'}</button></div></>:<div className={`${card} p-8 text-center`}><Info className="mx-auto text-blue-600"/><b className="mt-3 block">Leave types are not configured</b><p className="mt-2 text-sm text-slate-500">Ask your school administrator to configure leave types before applying.</p></div>}</div>}
