'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {Award,Bell,BookOpen,CalendarDays,Cake,Check,ChevronLeft,ChevronRight,Globe2,GraduationCap,KeyRound,Languages,LockKeyhole,Mail,MessageSquare,Save,Settings,ShieldCheck,Smartphone,UsersRound} from 'lucide-react';
import Sidebar from '@/components/sidebar';
import TopBar from '@/components/TopBar';
import {supabase} from '@/lib/supabase';

type Section='home'|'features'|'academics'|'notifications'|'security'|'system';
type Grade={grade:string;min:number;max:number;gpa?:number};
type Config={online_admissions_enabled:boolean;public_website_enabled:boolean;student_portal_enabled:boolean;teacher_portal_enabled:boolean;birthday_alerts_enabled:boolean;grading_system:string;grade_scale:Grade[];default_pass_mark:number;attendance_method:string;minimum_attendance_pct:number;low_attendance_alert_pct:number;settings_updated_at:string|null};
const defaults:Config={online_admissions_enabled:true,public_website_enabled:true,student_portal_enabled:true,teacher_portal_enabled:true,birthday_alerts_enabled:true,grading_system:'percentage',grade_scale:[],default_pass_mark:40,attendance_method:'daily',minimum_attendance_pct:75,low_attendance_alert_pct:75,settings_updated_at:null};
const menu=[
 {id:'features',title:'Feature Toggles',description:'Turn specific modules on or off for your school.',icon:Settings,tone:'bg-blue-50 text-blue-600 dark:bg-blue-950 dark:text-blue-300'},
 {id:'academics',title:'Academic Preferences',description:'Set rules for grading and attendance calculation.',icon:GraduationCap,tone:'bg-violet-50 text-violet-600 dark:bg-violet-950 dark:text-violet-300'},
 {id:'notifications',title:'Notification Preferences',description:'Control school and principal notifications.',icon:Bell,tone:'bg-amber-50 text-amber-600 dark:bg-amber-950 dark:text-amber-300'},
 {id:'security',title:'Security',description:'Manage account security and password.',icon:ShieldCheck,tone:'bg-rose-50 text-rose-600 dark:bg-rose-950 dark:text-rose-300'},
 {id:'system',title:'System Preferences',description:'Language, timezone and other school preferences.',icon:Languages,tone:'bg-emerald-50 text-emerald-600 dark:bg-emerald-950 dark:text-emerald-300'},
] as const;
const selectedKeys:Record<Exclude<Section,'home'>,(keyof Config)[]>={features:['online_admissions_enabled','public_website_enabled','student_portal_enabled','teacher_portal_enabled','birthday_alerts_enabled'],academics:['grading_system','grade_scale','default_pass_mark','attendance_method','minimum_attendance_pct','low_attendance_alert_pct'],notifications:[],security:[],system:[]};
function signature(value:Config,section:Section){return section==='home'?'':JSON.stringify(Object.fromEntries((selectedKeys[section]||[]).map(key=>[key,value[key]])));}

export default function SettingsExperience({section='home'}:{section?:Section}){
 const router=useRouter();const [schoolId,setSchoolId]=useState('');const [userId,setUserId]=useState('');const [saved,setSaved]=useState<Config>(defaults);const [config,setConfig]=useState<Config>(defaults);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const dirty=signature(config,section)!==signature(saved,section);const canSave=section==='features'||section==='academics';
 useEffect(()=>{let active=true;(async()=>{try{const {data:{user},error:authError}=await supabase.auth.getUser();if(authError||!user)throw new Error('Sign in to manage settings.');const {data:profile,error:profileError}=await supabase.from('profiles').select('school_id,role').eq('user_id',user.id).single();if(profileError||!profile?.school_id||!['admin','principal','school_admin'].includes(profile.role))throw new Error('Principal school access is required.');const {data,error:schoolError}=await supabase.from('schools').select('online_admissions_enabled,public_website_enabled,student_portal_enabled,teacher_portal_enabled,birthday_alerts_enabled,grading_system,grade_scale,default_pass_mark,attendance_method,minimum_attendance_pct,low_attendance_alert_pct,settings_updated_at').eq('id',profile.school_id).single();if(schoolError)throw schoolError;const next={...defaults,...data,grade_scale:Array.isArray(data.grade_scale)?data.grade_scale as unknown as Grade[]:[]};if(active){setSchoolId(profile.school_id);setUserId(user.id);setSaved(next);setConfig(next);}}catch(cause){if(active)setError(cause instanceof Error?cause.message:'Settings could not be loaded.');}finally{if(active)setLoading(false);}})();return()=>{active=false};},[]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function update<K extends keyof Config>(key:K,value:Config[K]){setConfig(current=>({...current,[key]:value}));setMessage('');setError('');}
 function validate(){if(config.default_pass_mark<0||config.default_pass_mark>100)return 'Pass mark must be between 0 and 100.';if(config.minimum_attendance_pct<0||config.minimum_attendance_pct>100)return 'Minimum attendance must be between 0 and 100.';if(config.low_attendance_alert_pct<0||config.low_attendance_alert_pct>config.minimum_attendance_pct)return 'Low-attendance threshold cannot exceed the minimum attendance requirement.';const sorted=[...config.grade_scale].sort((a,b)=>a.min-b.min);for(let i=0;i<sorted.length;i++){const row=sorted[i];if(!row.grade.trim()||row.min<0||row.max>100||row.min>row.max)return 'Every grade needs a name and a valid 0–100 range.';if(i&&row.min<=sorted[i-1].max)return 'Grade ranges cannot overlap.';}return '';}
 async function save(){if(!canSave||!dirty||!schoolId)return;const problem=validate();if(problem){setError(problem);return;}setSaving(true);setError('');setMessage('');const keys=selectedKeys[section as Exclude<Section,'home'>];const payload=Object.fromEntries(keys.map(key=>[key,config[key]]));const updatedAt=new Date().toISOString();const {data,error:saveError}=await supabase.from('schools').update({...payload,settings_updated_at:updatedAt,settings_updated_by:userId}).eq('id',schoolId).select('settings_updated_at').single();setSaving(false);if(saveError){setError(`Save failed: ${saveError.message}`);return;}const next={...config,settings_updated_at:data.settings_updated_at};setConfig(next);setSaved(next);setMessage('All changes saved');}
 const item=menu.find(value=>value.id===section);const title=section==='home'?'Settings & Preferences':item?.title||'Settings';const subtitle=section==='home'?"Configure your school's features, notifications, and academic rules.":item?.description||'';
 function goBack(){if(dirty&&!window.confirm('Discard your unsaved changes?'))return;router.push('/principal/settings');}
 return <div className="min-h-screen bg-slate-50 text-slate-950 dark:bg-slate-950 dark:text-white"><Sidebar/><div className="flex min-h-screen flex-col pt-10 lg:ml-64"><TopBar/><main className="flex-1 px-3 pb-24 pt-7 sm:px-6 lg:px-8 lg:pt-24"><div className="mx-auto max-w-3xl">
  <header className="mb-3">{section!=='home'&&<button onClick={goBack} aria-label="Back to settings" className="mb-2 rounded-lg p-1 hover:bg-slate-100 dark:hover:bg-slate-800"><ChevronLeft className="h-5 w-5"/></button>}<h1 className="text-xl font-extrabold sm:text-2xl">{title}</h1><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{subtitle}</p></header>
  {error&&<p role="alert" className="mb-2 rounded-lg bg-rose-50 p-2 text-xs text-rose-700 dark:bg-rose-950 dark:text-rose-300">{error}</p>}{message&&<p role="status" className="mb-2 flex items-center gap-1 rounded-lg bg-emerald-50 p-2 text-xs text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300"><Check className="h-3.5 w-3.5"/>{message}</p>}
  {loading?<div className="rounded-xl border border-slate-200 bg-white p-8 text-center text-xs text-slate-500 dark:border-slate-800 dark:bg-slate-900">Loading settings…</div>:section==='home'?<Home config={saved}/>:section==='features'?<Features config={config} update={update}/>:section==='academics'?<Academics config={config} update={update}/>:section==='notifications'?<Notifications/>:section==='security'?<Security/>:<System/>}
  {!loading&&canSave&&<div className="sticky bottom-16 mt-3 bg-slate-50/95 py-2 backdrop-blur dark:bg-slate-950/95 md:bottom-0"><button disabled={!dirty||saving} onClick={()=>void save()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving…':dirty?'Save Changes':'All changes saved'}</button>{config.settings_updated_at&&<p className="mt-1 text-center text-[10px] text-slate-500">Last updated {new Date(config.settings_updated_at).toLocaleString('en-NP',{timeZone:'Asia/Kathmandu'})}</p>}</div>}
 </div></main></div></div>;
}
function Home({config}:{config:Config}){return <><div className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">{menu.map(({id,title,description,icon:Icon,tone})=><Link key={id} href={`/principal/settings/${id}`} className="flex items-center gap-3 border-b border-slate-100 p-3 last:border-0 dark:border-slate-800"><span className={`rounded-lg p-2 ${tone}`}><Icon className="h-4 w-4"/></span><span className="min-w-0 flex-1"><strong className="block text-xs">{title}</strong><small className="block text-[10px] leading-4 text-slate-500">{description}</small></span><ChevronRight className="h-4 w-4 text-slate-400"/></Link>)}</div>{config.settings_updated_at&&<p className="mt-2 text-center text-[10px] text-slate-500">Last updated {new Date(config.settings_updated_at).toLocaleString('en-NP',{timeZone:'Asia/Kathmandu'})}</p>}</>}
function Features({config,update}:{config:Config;update:<K extends keyof Config>(key:K,value:Config[K])=>void}){return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><Toggle icon={UsersRound} title="Online Admissions" detail="Allow applications from the public school website." value={config.online_admissions_enabled} onChange={v=>update('online_admissions_enabled',v)}/><Toggle icon={Globe2} title="Public Website Visibility" detail="Make the approved school website visible publicly." value={config.public_website_enabled} onChange={v=>update('public_website_enabled',v)}/><Toggle icon={GraduationCap} title="Student Portal Access" detail="Allow verified students to open their portal." value={config.student_portal_enabled} onChange={v=>update('student_portal_enabled',v)}/><Toggle icon={BookOpen} title="Teacher Portal Access" detail="Allow verified teachers to open their portal." value={config.teacher_portal_enabled} onChange={v=>update('teacher_portal_enabled',v)}/><Toggle icon={Cake} title="Birthday Alerts" detail="Show upcoming staff birthday information." value={config.birthday_alerts_enabled} onChange={v=>update('birthday_alerts_enabled',v)}/><Unavailable icon={MessageSquare} title="SMS Notifications" detail="No SMS delivery provider is connected."/><Unavailable icon={Mail} title="Email Notifications" detail="General notification email delivery is not implemented."/></section>}
function Academics({config,update}:{config:Config;update:<K extends keyof Config>(key:K,value:Config[K])=>void}){const rows=config.grade_scale;function row(i:number,key:keyof Grade,value:string){update('grade_scale',rows.map((item,index)=>index===i?{...item,[key]:key==='grade'?value:Number(value)}:item))}return <div className="space-y-3"><Card icon={Award} title="Grading System"><select value={config.grading_system} onChange={e=>update('grading_system',e.target.value)} className={field}><option value="percentage">Percentage</option><option value="gpa">GPA</option><option value="both">GPA & Percentage</option></select></Card><Card icon={GraduationCap} title="Grading Scale"><div className="space-y-2">{rows.map((item,i)=><div key={i} className="grid grid-cols-[1fr_70px_70px_28px] gap-1"><input aria-label="Grade" value={item.grade} onChange={e=>row(i,'grade',e.target.value)} className={field}/><input aria-label="Minimum percent" type="number" min="0" max="100" value={item.min} onChange={e=>row(i,'min',e.target.value)} className={field}/><input aria-label="Maximum percent" type="number" min="0" max="100" value={item.max} onChange={e=>row(i,'max',e.target.value)} className={field}/><button aria-label="Remove grade range" onClick={()=>update('grade_scale',rows.filter((_,index)=>index!==i))} className="text-rose-600">×</button></div>)}<button onClick={()=>update('grade_scale',[...rows,{grade:'',min:0,max:100}])} className="w-full rounded-lg border border-blue-200 py-2 text-xs font-bold text-blue-600">+ Add Grade Range</button></div></Card><Card icon={Award} title="Default Pass Mark (%)"><NumberField value={config.default_pass_mark} onChange={v=>update('default_pass_mark',v)}/><p className="mt-1 text-[10px] text-slate-500">Used as the default when creating new exam subjects. Existing exams keep their saved pass marks.</p></Card><Card icon={CalendarDays} title="Attendance Calculation Method"><select value={config.attendance_method} disabled className={field}><option value="daily">Daily (Present / Absent / Late)</option></select><p className="mt-1 text-[10px] text-slate-500">Daily attendance is the only calculation method currently implemented.</p></Card><Card icon={CalendarDays} title="Attendance Thresholds"><div className="grid grid-cols-2 gap-2"><label className="text-[10px] text-slate-500">Minimum requirement (%)<NumberField value={config.minimum_attendance_pct} onChange={v=>update('minimum_attendance_pct',v)}/></label><label className="text-[10px] text-slate-500">Low-attendance alert (%)<NumberField value={config.low_attendance_alert_pct} onChange={v=>update('low_attendance_alert_pct',v)}/></label></div></Card></div>}
function Notifications(){const events=['New admissions','Fee payments / due reminders','Exams & results','Attendance alerts','Messages / communication','System updates','New notices'];return <div className="space-y-3"><section className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800 dark:border-amber-900 dark:bg-amber-950 dark:text-amber-200"><strong>Notification delivery is not configured.</strong><p className="mt-1">NEPSOM currently has no general in-app, email or SMS delivery pipeline, so these controls are disabled.</p></section><section className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><Unavailable icon={Smartphone} title="In-app notifications" detail="Unavailable"/><Unavailable icon={Mail} title="Email notifications" detail="Unavailable"/><Unavailable icon={MessageSquare} title="SMS notifications" detail="Unavailable"/></section><section className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900">{events.map(name=><div key={name} className="flex items-center border-b border-slate-100 p-3 text-xs last:border-0 dark:border-slate-800"><Bell className="mr-2 h-4 w-4 text-slate-400"/><span className="flex-1 font-semibold">{name}</span><span className="text-[10px] text-slate-400">Unavailable</span></div>)}</section></div>}
function Security(){return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><Link href="/principal/account/security" className="flex items-center gap-3 border-b border-slate-100 p-3 dark:border-slate-800"><span className="rounded-lg bg-blue-50 p-2 text-blue-600 dark:bg-blue-950"><KeyRound className="h-4 w-4"/></span><span className="flex-1"><strong className="block text-xs">Change Password</strong><small className="text-[10px] text-slate-500">Open the secure Supabase Auth password flow.</small></span><ChevronRight className="h-4 w-4 text-slate-400"/></Link><Unavailable icon={LockKeyhole} title="Two-Factor Authentication (2FA)" detail="Coming Soon"/></section>}
function System(){return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900"><Info icon={Languages} title="Language" value="English (Nepal)"/><Info icon={Globe2} title="Timezone" value="Asia/Kathmandu"/><Info icon={CalendarDays} title="Date format" value="DD/MM/YYYY"/><p className="border-t border-slate-100 p-3 text-[10px] text-slate-500 dark:border-slate-800">These are the locale rules currently supported throughout NEPSOM. More choices will appear only after matching formatting and translation support is implemented.</p></section>}
const field='mt-1 h-9 w-full rounded-lg border border-slate-200 bg-white px-2 text-xs text-slate-950 outline-none focus:border-blue-500 dark:border-slate-700 dark:bg-slate-800 dark:text-white';
function Toggle({icon:Icon,title,detail,value,onChange}:{icon:React.ElementType;title:string;detail:string;value:boolean;onChange:(value:boolean)=>void}){return <div className="flex items-center gap-3 border-b border-slate-100 p-3 last:border-0 dark:border-slate-800"><span className="rounded-lg bg-blue-50 p-2 text-blue-600 dark:bg-blue-950"><Icon className="h-4 w-4"/></span><span className="min-w-0 flex-1"><strong className="block text-xs">{title}</strong><small className="block text-[10px] leading-4 text-slate-500">{detail}</small></span><button type="button" role="switch" aria-checked={value} onClick={()=>onChange(!value)} className={`relative h-6 w-11 shrink-0 rounded-full ${value?'bg-blue-600':'bg-slate-300 dark:bg-slate-700'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${value?'left-6':'left-1'}`}/></button></div>}
function Unavailable({icon:Icon,title,detail}:{icon:React.ElementType;title:string;detail:string}){return <div className="flex items-center gap-3 border-b border-slate-100 p-3 last:border-0 dark:border-slate-800"><span className="rounded-lg bg-slate-100 p-2 text-slate-500 dark:bg-slate-800"><Icon className="h-4 w-4"/></span><span className="min-w-0 flex-1"><strong className="block text-xs">{title}</strong><small className="block text-[10px] text-slate-500">{detail}</small></span><span className="rounded-full bg-slate-100 px-2 py-1 text-[9px] font-bold text-slate-500 dark:bg-slate-800">Unavailable</span></div>}
function Card({icon:Icon,title,children}:{icon:React.ElementType;title:string;children:React.ReactNode}){return <section className="rounded-xl border border-slate-200 bg-white p-3 dark:border-slate-800 dark:bg-slate-900"><div className="mb-2 flex items-center gap-2"><span className="rounded-lg bg-violet-50 p-2 text-violet-600 dark:bg-violet-950"><Icon className="h-4 w-4"/></span><h2 className="text-xs font-bold">{title}</h2></div>{children}</section>}
function NumberField({value,onChange}:{value:number;onChange:(value:number)=>void}){return <input type="number" min="0" max="100" value={value} onChange={e=>onChange(Number(e.target.value))} className={field}/>}
function Info({icon:Icon,title,value}:{icon:React.ElementType;title:string;value:string}){return <div className="flex items-center gap-3 border-b border-slate-100 p-3 last:border-0 dark:border-slate-800"><span className="rounded-lg bg-emerald-50 p-2 text-emerald-600 dark:bg-emerald-950"><Icon className="h-4 w-4"/></span><span className="flex-1 text-xs font-semibold">{title}</span><span className="text-xs text-slate-500">{value}</span></div>}
