"use client";

import { useEffect, useState, type FormEvent, type ReactNode } from "react";
import Link from "next/link";
import NepaliDate from "nepali-date-converter";
import { ArrowLeft, BarChart3, BookOpen, CalendarDays, CheckCircle2, ChevronRight, Clock3, Loader2, Mail, MapPin, Phone, Search, SlidersHorizontal, UserRound, Users, XCircle } from "lucide-react";
import Sidebar from "@/components/sidebar";
import TopBar from "@/components/TopBar";
import { supabase } from "@/lib/supabase";
import { classLabel, className, matchesStudent, nepalClock, normalize, normalizeGrade, sectionName, type Assignment, type ClassRow } from "@/lib/teacher-classes";
import { ageOn, attendanceRate, attendanceStatus, belongsToClass, grade, type AttendanceRow, type Exam, type ExamMark, type ExamSubject, type StudentDetail } from "@/lib/teacher-students";

type Note = { id: string; student_id: string; title: string; content: string; created_at: string };
type Data = { schoolId: string; teacherId: string; userId: string; classes: ClassRow[]; assignments: Assignment[]; students: StudentDetail[]; attendance: AttendanceRow[]; exams: Exam[]; examSubjects: ExamSubject[]; marks: ExamMark[]; notes: Note[] };
type ClassTab = "Students" | "Attendance" | "Performance" | "Notes";
type StudentTab = "Overview" | "Attendance" | "Performance" | "Notes";
const classTabs: ClassTab[] = ["Students", "Attendance", "Performance", "Notes"];
const studentTabs: StudentTab[] = ["Overview", "Attendance", "Performance", "Notes"];
const panel = "rounded-[18px] border border-slate-200/80 bg-white shadow-[0_1px_3px_rgba(15,23,42,.04)] dark:border-slate-800 dark:bg-slate-900";
const muted = "text-slate-500 dark:text-slate-400";
const field = "h-12 w-full rounded-[14px] border border-slate-200 bg-slate-50/80 px-3 text-sm outline-none transition focus:border-blue-500 focus:bg-white focus:ring-2 focus:ring-blue-500/15 dark:border-slate-700 dark:bg-slate-900";

async function rows<T>(request: (from: number, to: number) => PromiseLike<{ data: unknown[] | null; error: { message: string } | null }>): Promise<T[]> {
  const all: T[] = [];
  for (let from = 0; ; from += 500) { const result = await request(from, from + 499); if (result.error) throw new Error(result.error.message); all.push(...((result.data || []) as T[])); if ((result.data || []).length < 500) return all; }
}
function Empty({ children }: { children: ReactNode }) { return <div className={`${panel} px-4 py-8 text-center text-sm ${muted}`}>{children}</div>; }
function Initials({ name, large = false }: { name: string; large?: boolean }) { return <span className={`flex shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-sky-100 to-blue-200 font-extrabold text-blue-700 dark:from-blue-950 dark:to-indigo-900 dark:text-blue-200 ${large ? "h-24 w-24 text-2xl" : "h-11 w-11 text-sm"}`}>{name.split(/\s+/).slice(0, 2).map((word) => word[0]).join("").toUpperCase()}</span>; }
function Badge({ status }: { status: string }) { const value = normalize(status); const cls = ["present", "late"].includes(value) ? "bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300" : value === "absent" ? "bg-rose-50 text-rose-700 dark:bg-rose-400/10 dark:text-rose-300" : ["leave", "on_leave", "on leave", "excused"].includes(value) ? "bg-amber-50 text-amber-700 dark:bg-amber-400/10 dark:text-amber-300" : "bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-300"; const label = value === "not marked" ? "Not marked" : value.replace("_", " ").replace(/^./, (c) => c.toUpperCase()); return <span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${cls}`}>{label}</span>; }
function Metric({ icon: Icon, value, label, tone }: { icon: typeof Users; value: ReactNode; label: string; tone: string }) { return <div className={`min-w-0 rounded-[16px] border border-white/70 p-2.5 text-center shadow-sm dark:border-white/5 sm:p-4 ${tone}`}><Icon className="mx-auto mb-1.5 h-5 w-5" /><p className="truncate text-xl font-extrabold tabular-nums sm:text-2xl">{value}</p><p className="mt-0.5 truncate text-[10px] font-medium text-slate-600 dark:text-slate-300 sm:text-xs">{label}</p></div>; }
function Tabs<T extends string>({ items, value, setValue }: { items: T[]; value: T; setValue: (value: T) => void }) { return <div role="tablist" className="-mx-3.5 flex overflow-x-auto border-b border-slate-200 bg-white px-3.5 dark:border-slate-800 dark:bg-slate-950 sm:mx-0 sm:px-0">{items.map((item) => <button key={item} role="tab" aria-selected={value === item} onClick={() => setValue(item)} className={`min-h-12 shrink-0 border-b-2 px-3 text-xs font-semibold sm:flex-1 sm:text-sm ${value === item ? "border-blue-600 text-blue-600 dark:text-blue-300" : `border-transparent ${muted}`}`}>{item}</button>)}</div>; }

export default function TeacherStudents({ classId, studentId }: { classId?: string; studentId?: string }) {
  const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [filters, setFilters] = useState(false); const [subject, setSubject] = useState(""); const [studentFilter, setStudentFilter] = useState(""); const [classTab, setClassTab] = useState<ClassTab>("Students"); const [studentTab, setStudentTab] = useState<StudentTab>("Overview"); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [saving, setSaving] = useState(false); const [refresh, setRefresh] = useState(0);
  const clock = nepalClock();
  useEffect(() => { let active = true; async function load() { setLoading(true); setError(""); try {
    const { data: auth, error: authError } = await supabase.auth.getUser(); if (authError || !auth.user) throw new Error("Please sign in with your teacher account.");
    const { data: profile, error: profileError } = await supabase.from("profiles").select("school_id,role").eq("user_id", auth.user.id).single(); if (profileError || profile?.role !== "teacher" || !profile.school_id) throw new Error("Teacher school access unavailable.");
    const { data: teacher, error: teacherError } = await supabase.from("teachers").select("id").eq("school_id", profile.school_id).eq("user_id", auth.user.id).is("left_at", null).single(); if (teacherError || !teacher) throw new Error("Active teacher membership unavailable.");
    const year = Number(new NepaliDate(new Date()).format("YYYY")); const schoolId = profile.school_id;
    const [assignments, classes, students, attendance, exams, examSubjects, marks, notes] = await Promise.all([
      rows<Assignment>((a,b)=>supabase.from("teacher_assignments").select("id,class_id,class_name,subject,period_id,weekday,periods_per_week,academic_year").eq("school_id",schoolId).eq("teacher_id",teacher.id).eq("active",true).range(a,b)),
      rows<ClassRow>((a,b)=>supabase.from("classes").select("id,school_id,class_name,class,name,class_number,section_name,section,academic_year,archived_at").eq("school_id",schoolId).eq("academic_year",year).is("archived_at",null).range(a,b)),
      rows<StudentDetail>((a,b)=>supabase.from("students").select("id,name,class,section,roll_no,gender,date_of_birth,dob,parent_name,parent_phone,address,email").eq("school_id",schoolId).range(a,b)),
      rows<AttendanceRow>((a,b)=>supabase.from("attendance").select("id,student_id,attendance_date,status").eq("school_id",schoolId).order("attendance_date",{ascending:false}).range(a,b)),
      rows<Exam>((a,b)=>supabase.from("exams").select("id,name,start_date,academic_year,published_at").eq("school_id",schoolId).not("published_at","is",null).range(a,b)),
      rows<ExamSubject>((a,b)=>supabase.from("exam_subjects").select("id,exam_id,class_name,section,subject_name,full_marks,pass_marks").eq("school_id",schoolId).range(a,b)),
      rows<ExamMark>((a,b)=>supabase.from("exam_marks").select("id,subject_id,student_id,marks").eq("school_id",schoolId).range(a,b)),
      rows<Note>((a,b)=>supabase.from("student_teacher_notes").select("id,student_id,title,content,created_at").eq("school_id",schoolId).order("created_at",{ascending:false}).range(a,b)),
    ]);
    const currentAssignments = assignments.filter((a)=>!a.academic_year || a.academic_year===String(year)); const assignedClasses = classes.filter((c)=>currentAssignments.some((a)=>a.class_id===c.id)).sort((a,b)=>classLabel(a).localeCompare(classLabel(b),undefined,{numeric:true})); const assignedStudents = students.filter((s)=>assignedClasses.some((c)=>matchesStudent(s,c))).sort((a,b)=>(a.roll_no||"").localeCompare(b.roll_no||"",undefined,{numeric:true})||a.name.localeCompare(b.name));
    if (active) setData({schoolId,teacherId:teacher.id,userId:auth.user.id,classes:assignedClasses,assignments:currentAssignments.filter((a)=>assignedClasses.some((c)=>c.id===a.class_id)),students:assignedStudents,attendance,exams,examSubjects,marks,notes});
  } catch(e) { if(active) setError(e instanceof Error?e.message:"Could not load assigned students."); } finally { if(active) setLoading(false); }} void load(); return()=>{active=false}; },[refresh]);

  const selectedClass = data?.classes.find((c)=>c.id===classId); const selectedStudent = selectedClass ? data?.students.find((s)=>s.id===studentId && belongsToClass(s,selectedClass)) : undefined; const classStudents = selectedClass ? data?.students.filter((s)=>belongsToClass(s,selectedClass))||[] : []; const assignedSubjects = selectedClass ? [...new Set(data?.assignments.filter((a)=>a.class_id===selectedClass.id).map((a)=>a.subject)||[])] : []; const todayRows = data?.attendance.filter((a)=>a.attendance_date===clock.date)||[];
  const statuses = (data?.students||[]).map((s)=>attendanceStatus(todayRows,s.id,clock.date)); const statusCount=(names:string[])=>statuses.filter((s)=>names.includes(s)).length;
  const visibleClasses=(data?.classes||[]).filter((c)=>{const own=data?.assignments.filter((a)=>a.class_id===c.id)||[]; const names=data?.students.filter((s)=>belongsToClass(s,c)).map((s)=>s.name).join(" ")||""; return `${classLabel(c)} ${own.map((a)=>a.subject).join(" ")} ${names}`.toLowerCase().includes(normalize(query))&&(!subject||own.some((a)=>a.subject===subject));});
  const visibleStudents=classStudents.filter((s)=>{const status=attendanceStatus(data?.attendance||[],s.id,clock.date); const matchesFilter=!studentFilter||(studentFilter==="present"&&["present","late"].includes(status))||(studentFilter==="leave"&&["leave","on_leave","on leave","excused"].includes(status))||studentFilter===status||normalize(s.gender)===studentFilter; return matchesFilter&&`${s.name} ${s.roll_no||""} ${s.gender||""}`.toLowerCase().includes(normalize(query));});
  const classSubjectRows = selectedClass ? (data?.examSubjects||[]).filter((s)=>normalizeGrade(s.class_name)===normalizeGrade(className(selectedClass))&&normalize(s.section)===normalize(sectionName(selectedClass))&&assignedSubjects.some((a)=>normalize(a)===normalize(s.subject_name))) : [];
  const classMarks=(data?.marks||[]).filter((m)=>classSubjectRows.some((s)=>s.id===m.subject_id)); const studentMarks=selectedStudent?classMarks.filter((m)=>m.student_id===selectedStudent.id):[];
  const performanceRows=(student:StudentDetail)=>studentMarks.filter((m)=>m.student_id===student.id).map((mark)=>{const sub=classSubjectRows.find((s)=>s.id===mark.subject_id)!; const exam=data?.exams.find((e)=>e.id===sub.exam_id); return {mark,sub,exam,percent:sub.full_marks?Math.round(Number(mark.marks)/Number(sub.full_marks)*100):0};}).filter((r)=>r.exam).sort((a,b)=>(b.exam?.start_date||"").localeCompare(a.exam?.start_date||""));
  async function saveNote(event:FormEvent){event.preventDefault(); if(!data||!selectedStudent||saving)return; setSaving(true); const {error:saveError}=await supabase.from("student_teacher_notes").insert({school_id:data.schoolId,student_id:selectedStudent.id,teacher_id:data.teacherId,title:title.trim(),content:content.trim(),created_by:data.userId}); setSaving(false); if(saveError){setError("Could not save this student note.");return;} setTitle("");setContent("");setRefresh((v)=>v+1);}

  return <div className="min-h-screen bg-[#f7f8fb] text-slate-900 dark:bg-slate-950 dark:text-slate-100"><Sidebar/><div className="flex min-h-screen flex-col pt-10 lg:ml-64"><TopBar/><main className="flex-1 px-3.5 pb-28 pt-20 sm:px-6 sm:pt-24 lg:px-8"><div className="mx-auto max-w-5xl space-y-4 sm:space-y-5">
    {(classId||studentId)&&<Link href={studentId?`/teacher/students/${classId}`:"/teacher/students"} className={`inline-flex items-center gap-2 text-sm font-semibold ${muted}`}><ArrowLeft size={18}/>{studentId?classLabel(selectedClass as ClassRow):"My Students"}</Link>}
    {loading?<div className="flex items-center justify-center gap-2 py-16"><Loader2 className="h-5 w-5 animate-spin text-blue-600"/>Loading students…</div>:error?<div role="alert" className={`${panel} p-5`}><p>{error}</p><button onClick={()=>setRefresh((v)=>v+1)} className="mt-3 text-sm font-bold text-blue-600">Try again</button></div>:classId&&!selectedClass?<Empty>This class is unavailable or is not assigned to you.</Empty>:studentId&&!selectedStudent?<Empty>This student is unavailable or is not enrolled in your assigned class.</Empty>:!classId?<>
      <header><h1 className="text-[28px] font-extrabold leading-tight tracking-[-.035em]">My Students</h1><p className={`mt-1 text-sm ${muted}`}>View students from your assigned classes.</p></header>
      <div className="flex gap-2"><label className="relative min-w-0 flex-1"><Search className={`absolute left-3.5 top-3.5 h-5 w-5 ${muted}`}/><input aria-label="Search students by name or class" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search students by name or class…" className={`${field} pl-11`}/></label><button aria-label="Filter classes" onClick={()=>setFilters((v)=>!v)} className={`${panel} flex h-12 w-12 items-center justify-center ${subject?"text-blue-600":muted}`}><SlidersHorizontal size={19}/></button></div>
      {filters&&<select className={field} value={subject} onChange={(e)=>setSubject(e.target.value)}><option value="">All assigned subjects</option>{[...new Set(data?.assignments.map((a)=>a.subject)||[])].sort().map((s)=><option key={s}>{s}</option>)}</select>}
      <div className="grid grid-cols-4 gap-2"><Metric icon={Users} value={data?.students.length||0} label="Total Students" tone="bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"/><Metric icon={UserRound} value={statusCount(["present","late"])} label="Present Today" tone="bg-blue-50 text-blue-700 dark:bg-blue-400/10 dark:text-blue-300"/><Metric icon={XCircle} value={statusCount(["absent"])} label="Absent Today" tone="bg-rose-50 text-rose-700 dark:bg-rose-400/10 dark:text-rose-300"/><Metric icon={Clock3} value={statusCount(["leave","on_leave","on leave","excused"])} label="On Leave" tone="bg-amber-50 text-amber-700 dark:bg-amber-400/10 dark:text-amber-300"/></div>
      <section className="space-y-3"><h2 className="text-base font-extrabold">Classes</h2><div className="grid gap-2.5 md:grid-cols-2">{visibleClasses.map((row,i)=>{const own=data?.assignments.filter((a)=>a.class_id===row.id)||[]; return <Link key={row.id} href={`/teacher/students/${row.id}`} className={`${panel} group flex min-h-[100px] items-center gap-3 p-3.5 transition hover:border-blue-300 hover:shadow-md`}><div className={`flex h-[74px] w-[64px] shrink-0 flex-col items-center justify-center rounded-[15px] ${["bg-blue-50 text-blue-700","bg-emerald-50 text-emerald-700","bg-amber-50 text-amber-700","bg-violet-50 text-violet-700"][i%4]}`}><span className="text-xl font-extrabold leading-none">{normalizeGrade(className(row))}</span><span className="mt-1 text-xs font-bold">{sectionName(row)||"—"}</span></div><div className="min-w-0 flex-1"><h3 className="font-extrabold">{classLabel(row)}</h3><p className={`mt-1 flex items-center gap-1 text-xs ${muted}`}><Users size={13}/>{data?.students.filter((s)=>belongsToClass(s,row)).length||0} students</p><p className={`mt-1 flex items-center gap-1 text-xs ${muted}`}><BookOpen size={13}/>{[...new Set(own.map((a)=>a.subject))].join(", ")||"No subject assigned"}</p></div><ChevronRight className={muted} size={19}/></Link>})}</div>{!visibleClasses.length&&<Empty>No assigned classes match your search.</Empty>}</section>
    </>:studentId&&selectedClass&&selectedStudent?<StudentProfile student={selectedStudent} row={selectedClass} tab={studentTab} setTab={setStudentTab} attendance={data!.attendance.filter((a)=>a.student_id===selectedStudent.id)} performance={performanceRows(selectedStudent)} notes={data!.notes.filter((n)=>n.student_id===selectedStudent.id)} title={title} content={content} setTitle={setTitle} setContent={setContent} saveNote={saveNote} saving={saving}/>:selectedClass&&<ClassView row={selectedClass} subjects={assignedSubjects} students={visibleStudents} allStudents={classStudents} data={data!} query={query} setQuery={setQuery} filters={filters} setFilters={setFilters} studentFilter={studentFilter} setStudentFilter={setStudentFilter} tab={classTab} setTab={setClassTab} today={clock.date} attendance={data!.attendance} subjectRows={classSubjectRows} marks={classMarks} notes={data!.notes}/>} 
  </div></main></div></div>;
}

function HeaderCard({ row, count, subjects }: { row: ClassRow; count: number; subjects: string[] }) { return <div className="relative overflow-hidden rounded-[20px] border border-blue-100 bg-gradient-to-br from-blue-50 via-sky-50 to-indigo-50 p-5 dark:border-blue-900/50 dark:from-blue-950/60 dark:via-slate-900 dark:to-indigo-950/50"><div className="absolute bottom-3 right-4 text-blue-200/70 dark:text-blue-700/30"><Users className="h-16 w-16" strokeWidth={1.4}/></div><div className="relative max-w-[80%]"><h1 className="text-2xl font-extrabold text-[#10245f] dark:text-blue-100">{classLabel(row)}</h1><p className={`mt-3 flex items-center gap-2 text-sm ${muted}`}><Users size={17}/>{count} students</p><p className={`mt-2 flex items-center gap-2 text-sm ${muted}`}><BookOpen size={17}/>{subjects.join(", ")||"No subject assigned"}</p><p className={`mt-2 flex items-center gap-2 text-sm ${muted}`}><CalendarDays size={17}/>{row.academic_year} Academic Year (BS)</p></div></div>; }

function ClassView({row,subjects,students,allStudents,data,query,setQuery,filters,setFilters,studentFilter,setStudentFilter,tab,setTab,today,attendance,subjectRows,marks,notes}:{row:ClassRow;subjects:string[];students:StudentDetail[];allStudents:StudentDetail[];data:Data;query:string;setQuery:(v:string)=>void;filters:boolean;setFilters:(v:boolean)=>void;studentFilter:string;setStudentFilter:(v:string)=>void;tab:ClassTab;setTab:(v:ClassTab)=>void;today:string;attendance:AttendanceRow[];subjectRows:ExamSubject[];marks:ExamMark[];notes:Note[]}) { const day=attendance.filter((a)=>a.attendance_date===today&&allStudents.some((s)=>s.id===a.student_id)); const count=(values:string[])=>day.filter((a)=>values.includes(normalize(a.status))).length; const dates=[...new Set(attendance.filter((a)=>allStudents.some((s)=>s.id===a.student_id)).map((a)=>a.attendance_date))].sort().reverse().slice(0,14); return <><HeaderCard row={row} count={allStudents.length} subjects={subjects}/><Tabs items={classTabs} value={tab} setValue={setTab}/>
  {tab==="Students"&&<div className="space-y-3"><div className="flex gap-2"><label className="relative min-w-0 flex-1"><Search className={`absolute left-3.5 top-3.5 h-5 w-5 ${muted}`}/><input className={`${field} pl-11`} value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search students…"/></label><button onClick={()=>setFilters(!filters)} aria-label="Filter students" className={`${panel} flex h-12 w-12 items-center justify-center ${studentFilter?"text-blue-600":muted}`}><SlidersHorizontal size={19}/></button></div>{filters&&<select aria-label="Filter student list" className={field} value={studentFilter} onChange={(e)=>setStudentFilter(e.target.value)}><option value="">All students</option><option value="present">Present today</option><option value="absent">Absent today</option><option value="leave">On leave today</option><option value="male">Male</option><option value="female">Female</option></select>}<div className={`${panel} divide-y divide-slate-100 overflow-hidden dark:divide-slate-800`}>{students.map((s,i)=><Link key={s.id} href={`/teacher/students/${row.id}/${s.id}`} className="flex items-center gap-3 p-3 transition hover:bg-slate-50 dark:hover:bg-slate-800"><span className={`w-5 text-center text-xs ${muted}`}>{s.roll_no||i+1}</span><Initials name={s.name}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{s.name}</p><p className={`mt-0.5 text-xs ${muted}`}>Roll No. {s.roll_no||"—"}{s.gender?`  |  ${s.gender}`:""}</p></div><Badge status={attendanceStatus(attendance,s.id,today)}/><ChevronRight size={18} className={muted}/></Link>)}</div>{!students.length&&<Empty>No students match your search.</Empty>}</div>}
  {tab==="Attendance"&&<div className="space-y-4"><div className="grid grid-cols-4 gap-2"><Metric icon={Users} value={allStudents.length} label="Students" tone="bg-blue-50 text-blue-700"/><Metric icon={CheckCircle2} value={count(["present","late"])} label="Present" tone="bg-emerald-50 text-emerald-700"/><Metric icon={XCircle} value={count(["absent"])} label="Absent" tone="bg-rose-50 text-rose-700"/><Metric icon={Clock3} value={count(["leave","on_leave","on leave","excused"])} label="Leave" tone="bg-amber-50 text-amber-700"/></div><section><h2 className="mb-3 font-extrabold">Attendance History</h2><div className={`${panel} divide-y divide-slate-100 dark:divide-slate-800`}>{dates.map((date)=>{const own=attendance.filter((a)=>a.attendance_date===date&&allStudents.some((s)=>s.id===a.student_id));return <div key={date} className="flex items-center justify-between p-3.5"><span className="text-sm font-semibold">{new Date(`${date}T00:00:00`).toLocaleDateString("en",{month:"short",day:"numeric",year:"numeric"})}</span><span className={`text-xs ${muted}`}>{own.filter((a)=>["present","late"].includes(normalize(a.status))).length} present · {own.filter((a)=>normalize(a.status)==="absent").length} absent</span></div>})}</div>{!dates.length&&<Empty>No attendance history yet.</Empty>}</section></div>}
  {tab==="Performance"&&<PerformanceList students={allStudents} subjects={subjectRows} marks={marks} exams={data.exams}/>} {tab==="Notes"&&<div className="space-y-3"><p className={`text-xs ${muted}`}>Student-specific notes appear inside each student profile and are visible only to assigned teachers.</p>{notes.length?<div className={`${panel} divide-y divide-slate-100 dark:divide-slate-800`}>{notes.slice(0,30).map((n)=><div key={n.id} className="p-3.5"><p className="text-sm font-bold">{allStudents.find((s)=>s.id===n.student_id)?.name||"Student"} · {n.title}</p><p className={`mt-1 text-xs ${muted}`}>{n.content}</p></div>)}</div>:<Empty>No student notes for this class yet.</Empty>}</div>}</>; }

function PerformanceList({students,subjects,marks,exams}:{students:StudentDetail[];subjects:ExamSubject[];marks:ExamMark[];exams:Exam[]}) { const rows=students.map((student)=>{const own=marks.filter((m)=>m.student_id===student.id&&subjects.some((s)=>s.id===m.subject_id));const percent=own.length?Math.round(own.reduce((n,m)=>{const s=subjects.find((x)=>x.id===m.subject_id)!;return n+(s.full_marks?Number(m.marks)/Number(s.full_marks)*100:0)},0)/own.length):null;return{student,percent,tests:new Set(own.map((m)=>subjects.find((s)=>s.id===m.subject_id)?.exam_id)).size};}).filter((r)=>r.percent!==null).sort((a,b)=>(b.percent||0)-(a.percent||0)); return <div className="space-y-3"><h2 className="font-extrabold">Published Results</h2>{rows.length?<div className={`${panel} divide-y divide-slate-100 dark:divide-slate-800`}>{rows.map((r)=><div key={r.student.id} className="flex items-center gap-3 p-3.5"><Initials name={r.student.name}/><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{r.student.name}</p><p className={`text-xs ${muted}`}>{r.tests} published {r.tests===1?"exam":"exams"}</p></div><div className="text-right"><p className="font-extrabold text-blue-700">{grade(r.percent)}</p><p className={`text-xs ${muted}`}>{r.percent}%</p></div></div>)}</div>:<Empty>No published results for your assigned subject yet.</Empty>}<p className={`text-xs ${muted}`}>Only published marks for this teacher&apos;s assigned class and subject are shown. {exams.length} published exams available.</p></div>; }

function StudentProfile({student,row,tab,setTab,attendance,performance,notes,title,content,setTitle,setContent,saveNote,saving}:{student:StudentDetail;row:ClassRow;tab:StudentTab;setTab:(v:StudentTab)=>void;attendance:AttendanceRow[];performance:{mark:ExamMark;sub:ExamSubject;exam:Exam|undefined;percent:number}[];notes:Note[];title:string;content:string;setTitle:(v:string)=>void;setContent:(v:string)=>void;saveNote:(e:FormEvent)=>void;saving:boolean}) { const dob=student.date_of_birth||student.dob; const age=ageOn(dob); const rate=attendanceRate(attendance,student.id); const average=performance.length?Math.round(performance.reduce((n,r)=>n+r.percent,0)/performance.length):null; return <><div className="relative overflow-hidden rounded-[20px] border border-blue-100 bg-gradient-to-br from-sky-50 to-blue-100 p-5 dark:border-blue-900/50 dark:from-blue-950/60 dark:to-slate-900"><div className="flex items-center gap-4"><Initials name={student.name} large/><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="truncate text-xl font-extrabold text-[#10245f] dark:text-blue-100">{student.name}</h1><span className="rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold text-emerald-700">Active</span></div><p className={`mt-2 text-sm ${muted}`}>{classLabel(row)} &nbsp;|&nbsp; Roll No. {student.roll_no||"—"}</p><p className={`mt-2 text-xs ${muted}`}>{student.gender||"Gender not recorded"}{dob?` · ${new Date(`${dob.slice(0,10)}T00:00:00`).toLocaleDateString("en",{month:"short",day:"numeric",year:"numeric"})}${age!==null?` (${age} years)`:""}`:""}</p></div></div></div><Tabs items={studentTabs} value={tab} setValue={setTab}/>
  {tab==="Overview"&&<div className="space-y-4"><div className="grid grid-cols-3 gap-2"><Metric icon={UserRound} value={rate===null?"—":`${rate}%`} label="Attendance" tone="bg-emerald-50 text-emerald-700"/><Metric icon={BarChart3} value={grade(average)} label="Subject Grade" tone="bg-blue-50 text-blue-700"/><Metric icon={BookOpen} value={new Set(performance.map((r)=>r.exam?.id)).size} label="Tests Taken" tone="bg-indigo-50 text-indigo-700"/></div><Info title="Personal Information" rows={[[UserRound,"Full Name",student.name],[CalendarDays,"Date of Birth",dob||"Not recorded"],[UserRound,"Gender",student.gender||"Not recorded"],[MapPin,"Address",student.address||"Not recorded"]]}/><Info title="Parent/Guardian Information" rows={[[UserRound,"Parent Name",student.parent_name||"Not recorded"],[Phone,"Phone",student.parent_phone||"Not recorded"],[Mail,"Email",student.email||"Not recorded"]]}/></div>}
  {tab==="Attendance"&&<div className="space-y-3"><div className="grid grid-cols-3 gap-2"><Metric icon={CheckCircle2} value={attendance.filter((a)=>["present","late"].includes(normalize(a.status))).length} label="Present" tone="bg-emerald-50 text-emerald-700"/><Metric icon={XCircle} value={attendance.filter((a)=>normalize(a.status)==="absent").length} label="Absent" tone="bg-rose-50 text-rose-700"/><Metric icon={Clock3} value={attendance.filter((a)=>["leave","on_leave","on leave","excused"].includes(normalize(a.status))).length} label="Leave" tone="bg-amber-50 text-amber-700"/></div><div className={`${panel} divide-y divide-slate-100 dark:divide-slate-800`}>{attendance.slice(0,60).map((a)=><div key={a.id} className="flex items-center justify-between p-3.5"><span className="text-sm font-semibold">{new Date(`${a.attendance_date}T00:00:00`).toLocaleDateString("en",{weekday:"short",month:"short",day:"numeric",year:"numeric"})}</span><Badge status={a.status}/></div>)}</div>{!attendance.length&&<Empty>No attendance records yet.</Empty>}</div>}
  {tab==="Performance"&&<div className="space-y-3">{performance.length?<div className={`${panel} divide-y divide-slate-100 dark:divide-slate-800`}>{performance.map((r)=><div key={r.mark.id} className="flex items-center gap-3 p-3.5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><BookOpen size={18}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{r.exam?.name}</p><p className={`text-xs ${muted}`}>{r.sub.subject_name} · {r.exam?.start_date}</p></div><div className="text-right"><p className="font-extrabold">{r.mark.marks}/{r.sub.full_marks}</p><p className={`text-xs ${muted}`}>{grade(r.percent)}</p></div></div>)}</div>:<Empty>No published results for your assigned subject.</Empty>}</div>}
  {tab==="Notes"&&<div className="space-y-3"><form onSubmit={saveNote} className={`${panel} space-y-3 p-4`}><input required maxLength={160} value={title} onChange={(e)=>setTitle(e.target.value)} placeholder="Note title" className={field}/><textarea required rows={4} maxLength={2000} value={content} onChange={(e)=>setContent(e.target.value)} placeholder="Write a private teaching note…" className={`${field} h-auto py-3`}/><button disabled={saving||!title.trim()||!content.trim()} className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?"Saving…":"Add note"}</button><p className={`text-[11px] ${muted}`}>Visible only to teachers assigned to this student&apos;s class.</p></form>{notes.length?<div className="space-y-2">{notes.map((n)=><article key={n.id} className={`${panel} p-4`}><h3 className="text-sm font-bold">{n.title}</h3><p className={`mt-1 text-[11px] ${muted}`}>{new Date(n.created_at).toLocaleDateString()}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{n.content}</p></article>)}</div>:<Empty>No teacher notes for this student yet.</Empty>}</div>}</>; }

function Info({title,rows}:{title:string;rows:[typeof UserRound,string,string][]}) { return <section className={`${panel} p-4`}><h2 className="mb-2 font-extrabold">{title}</h2><div className="divide-y divide-slate-100 dark:divide-slate-800">{rows.map(([Icon,label,value])=><div key={label} className="grid grid-cols-[24px_1fr_1.25fr] items-center gap-2 py-3 text-sm"><Icon size={18} className="text-slate-500"/><span className={muted}>{label}</span><span className="break-words font-medium">{value}</span></div>)}</div></section>; }
