'use client';
import {useCallback,useEffect,useState} from 'react';
import {BookOpen,CalendarDays,CheckCircle2,Download,FileText,Send,Upload,X} from 'lucide-react';
import Sidebar from '@/components/sidebar';
import TopBar from '@/components/TopBar';
import {supabase} from '@/lib/supabase';
import {formatBytes,validateAssignmentFile} from '@/lib/teacher-assignments';
type Assignment={id:string;school_id:string;title:string;subject:string;description:string|null;due_at:string;allow_late:boolean;assignment_type:string};
type Submission={id:string;assignment_id:string;submitted_at:string;feedback:string|null};
type AssignmentFile={id:string;assignment_id:string;storage_path:string;file_name:string;file_size:number};

export default function StudentAssignmentsPage(){
 const [student,setStudent]=useState<{id:string;school_id:string}|null>(null),[assignments,setAssignments]=useState<Assignment[]>([]),[submissions,setSubmissions]=useState<Submission[]>([]),[files,setFiles]=useState<AssignmentFile[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<Assignment|null>(null),[upload,setUpload]=useState<File|null>(null),[note,setNote]=useState(''),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const {data:auth}=await supabase.auth.getUser();if(!auth.user)throw Error('Please sign in.');const {data:s,error:se}=await supabase.from('students').select('id,school_id').eq('user_id',auth.user.id).single();if(se||!s)throw Error('Student access unavailable.');const [a,sub,f]=await Promise.all([supabase.from('assignments').select('id,school_id,title,subject,description,due_at,allow_late,assignment_type').eq('school_id',s.school_id).order('due_at'),supabase.from('assignment_submissions').select('id,assignment_id,submitted_at,feedback').eq('student_id',s.id),supabase.from('assignment_files').select('id,assignment_id,storage_path,file_name,file_size').eq('school_id',s.school_id)]);const issue=a.error||sub.error||f.error;if(issue)throw issue;setStudent(s);setAssignments((a.data||[]) as Assignment[]);setSubmissions((sub.data||[]) as Submission[]);setFiles((f.data||[]) as AssignmentFile[])}catch(reason){setError(reason instanceof Error?reason.message:'Could not load assignments.')}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 async function download(file:AssignmentFile){const result=await supabase.storage.from('assignment-files').createSignedUrl(file.storage_path,90,{download:file.file_name});if(result.error)setError(result.error.message);else location.assign(result.data.signedUrl)}
 function choose(file:File|null){if(!file){setUpload(null);return}const issue=validateAssignmentFile(file);if(issue){setError(issue);return}setError('');setUpload(file)}
 async function submit(){if(!selected||!student)return;if(!upload&&!note.trim()){setError('Add a file or submission note.');return}setSaving(true);setError('');let path='';try{const existing=submissions.find(s=>s.assignment_id===selected.id);const result=await supabase.from('assignment_submissions').upsert({assignment_id:selected.id,student_id:student.id,school_id:student.school_id,student_note:note.trim()||null,submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'assignment_id,student_id'}).select('id').single();if(result.error)throw result.error;if(upload){const ext=upload.name.split('.').pop()?.toLowerCase()||'file';path=`${student.school_id}/submissions/${result.data.id}/${(await supabase.auth.getUser()).data.user!.id}/${crypto.randomUUID()}.${ext}`;const up=await supabase.storage.from('assignment-files').upload(path,upload,{contentType:upload.type,upsert:false});if(up.error)throw up.error;const meta=await supabase.from('assignment_submission_files').insert({submission_id:result.data.id,school_id:student.school_id,storage_path:path,file_name:upload.name,mime_type:upload.type,file_size:upload.size});if(meta.error)throw meta.error}setSelected(null);setUpload(null);setNote('');await load();if(existing)setError('Submission updated successfully.')}catch(reason){if(path)await supabase.storage.from('assignment-files').remove([path]);setError(reason instanceof Error?reason.message:'Submission failed.')}finally{setSaving(false)}}
 if(loading)return <Shell><div className="mx-auto h-72 max-w-4xl animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800"/></Shell>;
 return <Shell><div className="mx-auto max-w-4xl space-y-4"><header><h1 className="text-3xl font-extrabold">Assignments</h1><p className="text-sm text-slate-500">View class work and submit your completed files.</p></header>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}<div className="grid gap-3 md:grid-cols-2">{assignments.map(a=>{const sub=submissions.find(s=>s.assignment_id===a.id),overdue=new Date(a.due_at)<new Date();return <article key={a.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-950"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><BookOpen/></span><span className={`rounded-full px-2 py-1 text-xs ${sub?'bg-emerald-100 text-emerald-700':overdue?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{sub?'Submitted':overdue?'Overdue':'Pending'}</span></div><h2 className="mt-3 text-lg font-bold">{a.title}</h2><p className="text-sm text-slate-500">{a.subject} · {a.assignment_type}</p><p className="mt-3 line-clamp-3 text-sm">{a.description||'No additional instructions.'}</p><p className="mt-3 text-xs text-slate-500"><CalendarDays className="mr-1 inline h-4 w-4"/>Due {new Date(a.due_at).toLocaleString()}</p>{files.filter(f=>f.assignment_id===a.id).map(f=><button key={f.id} onClick={()=>download(f)} className="mt-2 flex w-full items-center gap-2 rounded-xl bg-slate-50 p-2 text-sm dark:bg-slate-900"><FileText className="h-4 w-4"/><span className="flex-1 truncate text-left">{f.file_name}</span><Download className="h-4 w-4"/></button>)}<button disabled={!sub&&overdue&&!a.allow_late} onClick={()=>setSelected(a)} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-2.5 font-semibold text-white disabled:bg-slate-300"><Send className="h-4 w-4"/>{sub?'Update Submission':'Submit Assignment'}</button>{sub?.feedback&&<p className="mt-3 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800">Teacher feedback: {sub.feedback}</p>}</article>})}</div>{!assignments.length&&<div className="rounded-2xl border border-dashed p-10 text-center"><CheckCircle2 className="mx-auto text-emerald-500"/><b className="mt-3 block">No assigned work</b></div>}
 {selected&&<div className="fixed inset-0 z-50 grid place-items-end bg-black/40 p-0 sm:place-items-center sm:p-4"><div className="w-full max-w-lg rounded-t-3xl bg-white p-5 dark:bg-slate-950 sm:rounded-3xl"><div className="flex items-center justify-between"><h2 className="font-bold">Submit {selected.title}</h2><button onClick={()=>setSelected(null)}><X/></button></div><textarea value={note} onChange={e=>setNote(e.target.value)} rows={4} placeholder="Add a note for your teacher…" className="mt-4 w-full rounded-xl border p-3 dark:border-slate-700 dark:bg-slate-900"/><label className="mt-3 flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-blue-50 p-3 font-semibold text-blue-600"><Upload/>Choose file<input type="file" className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png,.webp" onChange={e=>choose(e.target.files?.[0]||null)}/></label>{upload&&<p className="mt-2 text-sm">{upload.name} · {formatBytes(upload.size)}</p>}<button onClick={submit} disabled={saving} className="mt-4 w-full rounded-xl bg-blue-600 py-3 font-semibold text-white">{saving?'Submitting…':'Submit'}</button></div></div>}</div></Shell>
}
function Shell({children}:{children:React.ReactNode}){return <div className="min-h-screen bg-slate-50 text-slate-950 dark:bg-slate-950 dark:text-white"><Sidebar/><div className="min-h-screen pt-10 lg:ml-64"><TopBar/><main className="px-4 pb-24 pt-24 sm:px-6 lg:px-8">{children}</main></div></div>}
