'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowLeft,BookOpen,CalendarDays,CheckCircle2,ChevronRight,Clock3,Download,FileText,Filter,MessageSquare,Plus,Save,Search,Trash2,Upload,Users,X} from 'lucide-react';
import Sidebar from '@/components/sidebar';
import TopBar from '@/components/TopBar';
import {supabase} from '@/lib/supabase';
import {assignmentStatus,formatBytes,normalizeClass,validateAssignmentFile} from '@/lib/teacher-assignments';

type Mode='home'|'create'|'detail'|'submission';
type Assignment={id:string;school_id:string;teacher_id:string;class_id:string;title:string;subject:string;assignment_type:string;description:string|null;due_at:string;allow_late:boolean;target_mode:string;status:string;created_at:string;updated_at:string};
type TeacherAssignment={class_id:string;subject:string};
type ClassRow={id:string;class_name:string|null;class:string|null;name:string|null;class_number:string|null;section:string|null;section_name:string|null};
type Student={id:string;name:string;class:string|null;section:string|null;roll_no:string|null};
type Submission={id:string;assignment_id:string;student_id:string;submitted_at:string;student_note:string|null;feedback:string|null;feedback_updated_at:string|null};
type StoredFile={id:string;storage_path:string;file_name:string;mime_type:string;file_size:number};
type Context={userId:string;schoolId:string;teacherId:string;assignments:Assignment[];teacherAssignments:TeacherAssignment[];classes:ClassRow[];students:Student[];submissions:Submission[];targets:{assignment_id:string;student_id:string}[];files:StoredFile[]};
const card='rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-950';
const input='w-full rounded-xl border border-slate-200 bg-transparent px-3 py-2.5 text-sm outline-none focus:border-blue-500 dark:border-slate-700';
const classLabel=(c?:ClassRow)=>c?[c.class_name||c.class||c.name||c.class_number,c.section_name||c.section].filter(Boolean).join(' '):'Class';
const dueLabel=(value:string)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value));
const rollSort=(a:Student,b:Student)=>(a.roll_no||'').localeCompare(b.roll_no||'',undefined,{numeric:true})||a.name.localeCompare(b.name);
function belongs(student:Student,cls:ClassRow){return normalizeClass(student.class)===normalizeClass(cls.class_name||cls.class||cls.name||cls.class_number)&&normalizeClass(student.section)===normalizeClass(cls.section_name||cls.section)}

export default function TeacherAssignments({mode,assignmentId,studentId}:{mode:Mode;assignmentId?:string;studentId?:string}){
 const router=useRouter(),[ctx,setCtx]=useState<Context|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const {data:auth}=await supabase.auth.getUser();if(!auth.user)throw Error('Please sign in with your teacher account.');const {data:p}=await supabase.from('profiles').select('school_id,role').eq('user_id',auth.user.id).single();if(p?.role!=='teacher'||!p.school_id)throw Error('Teacher access unavailable.');const {data:t}=await supabase.from('teachers').select('id').eq('school_id',p.school_id).eq('user_id',auth.user.id).is('left_at',null).single();if(!t)throw Error('Active teacher membership unavailable.');const [ar,tar,cr,sr,sur,tr,fr]=await Promise.all([
  supabase.from('assignments').select('*').eq('school_id',p.school_id).eq('teacher_id',t.id).order('created_at',{ascending:false}),
  supabase.from('teacher_assignments').select('class_id,subject').eq('school_id',p.school_id).eq('teacher_id',t.id).eq('active',true),
  supabase.from('classes').select('id,class_name,class,name,class_number,section,section_name').eq('school_id',p.school_id).is('archived_at',null),
  supabase.from('students').select('id,name,class,section,roll_no').eq('school_id',p.school_id),
  supabase.from('assignment_submissions').select('id,assignment_id,student_id,submitted_at,student_note,feedback,feedback_updated_at').eq('school_id',p.school_id),
  supabase.from('assignment_targets').select('assignment_id,student_id').eq('school_id',p.school_id),
  supabase.from('assignment_files').select('id,assignment_id,storage_path,file_name,mime_type,file_size').eq('school_id',p.school_id),
 ]);const failed=[ar,tar,cr,sr,sur,tr,fr].find(r=>r.error);if(failed?.error)throw failed.error;setCtx({userId:auth.user.id,schoolId:p.school_id,teacherId:t.id,assignments:(ar.data||[]) as Assignment[],teacherAssignments:(tar.data||[]) as TeacherAssignment[],classes:(cr.data||[]) as ClassRow[],students:((sr.data||[]) as Student[]).sort(rollSort),submissions:(sur.data||[]) as Submission[],targets:(tr.data||[]) as {assignment_id:string;student_id:string}[],files:(fr.data||[]) as StoredFile[]});}catch(reason){setError(reason instanceof Error?reason.message:'Could not load assignments.')}finally{setLoading(false)}},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),0);return()=>clearTimeout(timer)},[load]);
 if(loading)return <Shell><div className="mx-auto max-w-4xl animate-pulse space-y-3"><div className="h-24 rounded-2xl bg-slate-200 dark:bg-slate-800"/><div className="h-72 rounded-2xl bg-slate-200 dark:bg-slate-800"/></div></Shell>;
 if(error||!ctx)return <Shell><ErrorState message={error} retry={load}/></Shell>;
 if(mode==='create')return <Shell><Create ctx={ctx} back={()=>router.back()}/></Shell>;
 const assignment=assignmentId?ctx.assignments.find(a=>a.id===assignmentId):undefined;
 if(mode!=='home'&&!assignment)return <Shell><ErrorState message="This assignment is unavailable or is not owned by you." retry={()=>router.push('/teacher/assignments')}/></Shell>;
 if(mode==='submission')return <Shell><SubmissionDetail ctx={ctx} assignment={assignment!} studentId={studentId!} back={()=>router.back()} refresh={load}/></Shell>;
 if(mode==='detail')return <Shell><AssignmentDetail ctx={ctx} assignment={assignment!} back={()=>router.back()} refresh={load}/></Shell>;
 return <Shell><Home ctx={ctx}/></Shell>;
}

function Home({ctx}:{ctx:Context}){
 const [filter,setFilter]=useState('All'),[query,setQuery]=useState('');
 const enriched=ctx.assignments.map(a=>{const total=assignedStudents(ctx,a).length,submitted=ctx.submissions.filter(s=>s.assignment_id===a.id).length;return{a,total,submitted,status:assignmentStatus(a,submitted,total)}});
 const shown=enriched.filter(x=>(filter==='All'||x.status===filter)&&(`${x.a.title} ${x.a.subject} ${classLabel(ctx.classes.find(c=>c.id===x.a.class_id))}`.toLowerCase().includes(query.toLowerCase())));
 const count=(status:string)=>enriched.filter(x=>x.status===status).length;
 return <div className="mx-auto max-w-4xl space-y-4"><header><h1 className="text-3xl font-extrabold">Assignments</h1><p className="text-sm text-slate-500">Create and manage assignments for your classes.</p></header>
 <div className="grid grid-cols-4 gap-2"><Stat icon={FileText} value={enriched.length} label="Total" tone="blue"/><Stat icon={CheckCircle2} value={count('Active')} label="Active" tone="green"/><Stat icon={Clock3} value={count('Pending')} label="Pending" tone="amber"/><Stat icon={Download} value={count('Overdue')} label="Overdue" tone="rose"/></div>
 <div className="flex overflow-x-auto border-b dark:border-slate-800">{['All','Active','Pending','Overdue','Completed'].map(value=><button key={value} onClick={()=>setFilter(value)} className={`min-w-fit border-b-2 px-3 py-2 text-sm ${filter===value?'border-blue-600 font-semibold text-blue-600':'border-transparent text-slate-500'}`}>{value}</button>)}</div>
 <div className="flex gap-2"><label className={`${card} flex flex-1 items-center gap-2 px-3`}><Search className="h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search assignments…" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none"/></label><button aria-label="Filter assignments" className={`${card} p-3`}><Filter className="h-5 w-5"/></button></div>
 <div className="space-y-2">{shown.map(({a,total,status},index)=><Link href={`/teacher/assignments/${a.id}`} key={a.id} className={`${card} grid grid-cols-[48px_1fr_auto] items-center gap-3 p-3`}><span className={`grid h-12 w-12 place-items-center rounded-xl ${['bg-emerald-50 text-emerald-600','bg-violet-50 text-violet-600','bg-rose-50 text-rose-600','bg-blue-50 text-blue-600'][index%4]}`}><FileText/></span><div className="min-w-0"><b className="block truncate">{a.title}</b><p className="truncate text-xs text-slate-500">{a.subject} · {classLabel(ctx.classes.find(c=>c.id===a.class_id))}</p><p className="mt-1 flex gap-4 text-xs text-slate-500"><span><CalendarDays className="mr-1 inline h-3 w-3"/>Due {dueLabel(a.due_at)}</span><span><Users className="mr-1 inline h-3 w-3"/>{total} students</span></p></div><div className="flex items-center gap-1"><Badge status={status}/><ChevronRight className="h-4 w-4 text-slate-400"/></div></Link>)}</div>
 {!shown.length&&<Empty title="No assignments found" body={ctx.assignments.length?'Try another search or filter.':'Create your first real assignment for an assigned class.'}/>}
 <Link href="/teacher/assignments/create" className="sticky bottom-20 mx-auto flex w-full max-w-sm items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white shadow-lg"><Plus/>Create Assignment</Link></div>
}

function Create({ctx,back}:{ctx:Context;back:()=>void}){
 const router=useRouter(),[title,setTitle]=useState(''),[classId,setClassId]=useState(''),[subject,setSubject]=useState(''),[type,setType]=useState('homework'),[description,setDescription]=useState(''),[dueDate,setDueDate]=useState(''),[dueTime,setDueTime]=useState('23:59'),[allowLate,setAllowLate]=useState(false),[targetMode,setTargetMode]=useState<'class'|'students'>('class'),[selected,setSelected]=useState<string[]>([]),[file,setFile]=useState<File|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const classOptions=ctx.classes.filter(c=>ctx.teacherAssignments.some(a=>a.class_id===c.id));const subjects=Array.from(new Set(ctx.teacherAssignments.filter(a=>a.class_id===classId).map(a=>a.subject)));const cls=ctx.classes.find(c=>c.id===classId),students=cls?ctx.students.filter(s=>belongs(s,cls)):[];
 function chooseFile(next:File|null){if(!next){setFile(null);return}const issue=validateAssignmentFile(next);if(issue){setError(issue);return}setError('');setFile(next)}
 async function create(){if(!title.trim()||!classId||!subject||!dueDate){setError('Title, subject, class, and due date are required.');return}if(targetMode==='students'&&!selected.length){setError('Select at least one student.');return}setSaving(true);setError('');let createdId='';let path='';try{const dueAt=new Date(`${dueDate}T${dueTime}:00+05:45`).toISOString();const result=await supabase.from('assignments').insert({school_id:ctx.schoolId,teacher_id:ctx.teacherId,class_id:classId,title:title.trim(),subject,assignment_type:type,description:description.trim()||null,due_at:dueAt,allow_late:allowLate,target_mode:targetMode,created_by:ctx.userId}).select('id').single();if(result.error)throw result.error;createdId=result.data.id;if(targetMode==='students'){const target=await supabase.from('assignment_targets').insert(selected.map(student_id=>({assignment_id:createdId,student_id,school_id:ctx.schoolId})));if(target.error)throw target.error}if(file){const ext=file.name.split('.').pop()?.toLowerCase()||'file';path=`${ctx.schoolId}/assignments/${createdId}/${ctx.userId}/${crypto.randomUUID()}.${ext}`;const upload=await supabase.storage.from('assignment-files').upload(path,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;const record=await supabase.from('assignment_files').insert({assignment_id:createdId,school_id:ctx.schoolId,storage_path:path,file_name:file.name,mime_type:file.type,file_size:file.size});if(record.error)throw record.error}router.push(`/teacher/assignments/${createdId}`)}catch(reason){if(path)await supabase.storage.from('assignment-files').remove([path]);if(createdId)await supabase.from('assignments').delete().eq('id',createdId);setError(reason instanceof Error?reason.message:'Could not create assignment.')}finally{setSaving(false)}}
 return <div className="mx-auto max-w-2xl space-y-4"><Header back={back} title="Create Assignment"/><section className={`${card} space-y-4 p-4`}><Field label="Assignment Title *"><input value={title} onChange={e=>setTitle(e.target.value)} className={input} maxLength={180}/></Field><Field label="Class / section *"><select value={classId} onChange={e=>{setClassId(e.target.value);setSubject('');setSelected([])}} className={input}><option value="">Select class</option>{classOptions.map(c=><option key={c.id} value={c.id}>{classLabel(c)}</option>)}</select></Field><div className="grid grid-cols-2 gap-3"><Field label="Subject *"><select value={subject} onChange={e=>setSubject(e.target.value)} className={input}><option value="">Select subject</option>{subjects.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Type"><select value={type} onChange={e=>setType(e.target.value)} className={input}>{['homework','project','worksheet','practical','reading','other'].map(v=><option key={v} value={v}>{v[0].toUpperCase()+v.slice(1)}</option>)}</select></Field></div><Field label="Description / instructions"><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={5} maxLength={4000} className={` resize-none`}/></Field>
 <Field label="Attachment (optional)"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-blue-50 p-3 text-sm font-semibold text-blue-600 dark:bg-blue-950/40"><Upload className="h-4 w-4"/>Upload file<input type="file" className="hidden" accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png,.webp" onChange={e=>chooseFile(e.target.files?.[0]||null)}/></label>{file&&<div className="mt-2 flex items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-900"><FileText className="text-blue-600"/><div className="min-w-0 flex-1"><b className="block truncate text-sm">{file.name}</b><span className="text-xs text-slate-500">{formatBytes(file.size)}</span></div><button onClick={()=>chooseFile(null)}><X/></button></div>}</Field>
 <div className="grid grid-cols-2 gap-3"><Field label="Due date *"><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className={input}/></Field><Field label="Due time"><input type="time" value={dueTime} onChange={e=>setDueTime(e.target.value)} className={input}/></Field></div>
 <Field label="Assign to"><label className="block py-2"><input type="radio" checked={targetMode==='class'} onChange={()=>setTargetMode('class')}/> Entire selected class ({students.length} students)</label><label className="block py-2"><input type="radio" checked={targetMode==='students'} onChange={()=>setTargetMode('students')}/> Specific students</label>{targetMode==='students'&&<div className="max-h-48 overflow-auto rounded-xl border p-2 dark:border-slate-700">{students.map(s=><label key={s.id} className="flex gap-2 p-2 text-sm"><input type="checkbox" checked={selected.includes(s.id)} onChange={()=>setSelected(v=>v.includes(s.id)?v.filter(id=>id!==s.id):[...v,s.id])}/>{s.roll_no||'—'} · {s.name}</label>)}</div>}</Field>
 <label className="flex items-center justify-between"><span>Allow Late Submission</span><input type="checkbox" checked={allowLate} onChange={e=>setAllowLate(e.target.checked)} className="h-5 w-5"/></label>{error&&<p className="text-sm text-red-600">{error}</p>}</section><div className="grid grid-cols-2 gap-3"><button onClick={back} className="rounded-xl bg-slate-100 py-3 font-semibold dark:bg-slate-800">Cancel</button><button onClick={create} disabled={saving} className="rounded-xl bg-blue-600 py-3 font-semibold text-white disabled:opacity-50">{saving?'Creating…':'Create Assignment'}</button></div></div>
}

function AssignmentDetail({ctx,assignment,back,refresh}:{ctx:Context;assignment:Assignment;back:()=>void;refresh:()=>Promise<void>}){
 const router=useRouter(),[tab,setTab]=useState<'Submissions'|'Details'|'Analytics'>('Submissions'),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const [title,setTitle]=useState(assignment.title),[description,setDescription]=useState(assignment.description||''),[due,setDue]=useState(assignment.due_at.slice(0,16)),[allowLate,setAllowLate]=useState(assignment.allow_late);
 const [now]=useState(()=>Date.now());const cls=ctx.classes.find(c=>c.id===assignment.class_id),students=assignedStudents(ctx,assignment),submissions=ctx.submissions.filter(s=>s.assignment_id===assignment.id),files=ctx.files.filter(f=>(f as StoredFile&{assignment_id?:string}).assignment_id===assignment.id),byStudent=new Map(submissions.map(s=>[s.student_id,s]));
 const submitted=submissions.length,late=submissions.filter(s=>new Date(s.submitted_at)>new Date(assignment.due_at)).length,pending=students.filter(s=>!byStudent.has(s.id)&&new Date(assignment.due_at).getTime()>=now).length,missing=students.length-submitted-pending;
 const shown=students.filter(s=>{const submission=byStudent.get(s.id),status=submission?(new Date(submission.submitted_at)>new Date(assignment.due_at)?'Late':'Submitted'):(new Date(assignment.due_at).getTime()<now?'Not Submitted':'Pending');return(filter==='All'||filter===status)&&(`${s.name} ${s.roll_no||''}`.toLowerCase().includes(query.toLowerCase()))});
 async function download(file:StoredFile){const result=await supabase.storage.from('assignment-files').createSignedUrl(file.storage_path,90,{download:file.file_name});if(result.error){setError(result.error.message);return}location.assign(result.data.signedUrl)}
 async function save(){setSaving(true);setError('');const result=await supabase.from('assignments').update({title:title.trim(),description:description.trim()||null,due_at:new Date(`${due}:00+05:45`).toISOString(),allow_late:allowLate,updated_at:new Date().toISOString()}).eq('id',assignment.id).eq('teacher_id',ctx.teacherId);setSaving(false);if(result.error)setError(result.error.message);else await refresh()}
 async function remove(){if(!confirm('Delete this assignment and all related submissions? This cannot be undone.'))return;setSaving(true);for(const file of files)await supabase.storage.from('assignment-files').remove([file.storage_path]);const result=await supabase.from('assignments').delete().eq('id',assignment.id).eq('teacher_id',ctx.teacherId);if(result.error){setError(result.error.message);setSaving(false)}else router.push('/teacher/assignments')}
 return <div className="mx-auto max-w-4xl space-y-4"><Header back={back} title={assignment.title}/><section className="rounded-2xl bg-gradient-to-br from-blue-50 to-sky-100 p-4 dark:from-blue-950 dark:to-slate-900"><div className="flex gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-blue-500 text-white"><BookOpen/></span><div className="min-w-0 flex-1"><h1 className="truncate text-xl font-extrabold">{assignment.title}</h1><p className="text-sm">{assignment.subject} · {classLabel(cls)}</p></div><Badge status={assignmentStatus(assignment,submitted,students.length)}/></div><div className="mt-4 grid gap-2 text-sm text-slate-600 dark:text-slate-300"><span><CalendarDays className="mr-2 inline h-4 w-4 text-blue-600"/>Due: {dueLabel(assignment.due_at)}</span><span><FileText className="mr-2 inline h-4 w-4 text-blue-600"/>{assignment.assignment_type}</span><span><Users className="mr-2 inline h-4 w-4 text-blue-600"/>{students.length} students · {files.length} attachment{files.length===1?'':'s'}</span></div></section>
 <Tabs values={['Submissions','Details','Analytics']} active={tab} set={v=>setTab(v as typeof tab)}/>
 {tab==='Submissions'&&<><div className="grid grid-cols-4 gap-2"><Stat icon={Users} value={students.length} label="Total" tone="blue"/><Stat icon={CheckCircle2} value={submitted} label="Submitted" tone="green"/><Stat icon={Clock3} value={pending} label="Pending" tone="amber"/><Stat icon={Download} value={missing} label="Not Submitted" tone="rose"/></div><div className="flex gap-2"><label className={`${card} flex flex-1 items-center gap-2 px-3`}><Search className="h-4 w-4"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search students…" className="w-full bg-transparent py-3 text-sm outline-none"/></label><select value={filter} onChange={e=>setFilter(e.target.value)} className={`${card} px-3 text-sm`}>{['All','Submitted','Late','Pending','Not Submitted'].map(v=><option key={v}>{v}</option>)}</select></div><div className={`${card} divide-y dark:divide-slate-800`}>{shown.map(s=>{const sub=byStudent.get(s.id),status=sub?(new Date(sub.submitted_at)>new Date(assignment.due_at)?'Late':'Submitted'):(new Date(assignment.due_at).getTime()<now?'Not Submitted':'Pending');return <Link href={`/teacher/assignments/${assignment.id}/${s.id}`} key={s.id} className="grid grid-cols-[28px_40px_1fr_auto] items-center gap-2 p-3"><span className="text-xs">{s.roll_no||'—'}</span><span className="grid h-9 w-9 place-items-center rounded-full bg-blue-100 font-bold text-blue-700">{s.name[0]}</span><div><b className="block text-sm">{s.name}</b><span className="text-xs text-slate-500">{sub?dueLabel(sub.submitted_at):'—'}</span></div><div className="flex items-center gap-1"><Badge status={status}/><ChevronRight className="h-4 w-4"/></div></Link>})}</div></>}
 {tab==='Details'&&<section className={`${card} space-y-4 p-4`}><Field label="Title"><input className={input} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Instructions"><textarea className={input} rows={5} value={description} onChange={e=>setDescription(e.target.value)}/></Field><Field label="Due date and time"><input className={input} type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></Field><label className="flex justify-between">Allow late submission<input type="checkbox" checked={allowLate} onChange={e=>setAllowLate(e.target.checked)}/></label><div><b className="text-sm">Attachments</b>{files.length?files.map(f=><button key={f.id} onClick={()=>download(f)} className="mt-2 flex w-full items-center gap-3 rounded-xl bg-slate-50 p-3 text-left dark:bg-slate-900"><FileText/><span className="flex-1 truncate">{f.file_name}</span><Download className="h-4 w-4"/></button>):<p className="mt-2 text-sm text-slate-500">No attachments.</p>}</div><p className="text-xs text-slate-500">Created {dueLabel(assignment.created_at)} · Target: {assignment.target_mode==='class'?'Entire class':'Specific students'}</p>{error&&<p className="text-sm text-red-600">{error}</p>}<div className="grid grid-cols-2 gap-3"><button onClick={remove} disabled={saving} className="flex items-center justify-center gap-2 rounded-xl bg-red-50 py-3 font-semibold text-red-600"><Trash2 className="h-4 w-4"/>Delete</button><button onClick={save} disabled={saving||!title.trim()} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 font-semibold text-white"><Save className="h-4 w-4"/>{saving?'Saving…':'Save Changes'}</button></div></section>}
 {tab==='Analytics'&&<section className={`${card} p-4`}><h2 className="font-bold">Submission Analytics</h2><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Submission rate" value={students.length?`${Math.round(submitted/students.length*100)}%`:'—'}/><Metric label="On time" value={String(submitted-late)}/><Metric label="Late" value={String(late)}/><Metric label="Awaiting submission" value={String(pending+missing)}/></div>{!students.length&&<p className="mt-4 text-sm text-slate-500">Analytics will appear when students are assigned.</p>}</section>}</div>
}

function SubmissionDetail({ctx,assignment,studentId,back,refresh}:{ctx:Context;assignment:Assignment;studentId:string;back:()=>void;refresh:()=>Promise<void>}){
 const submission=ctx.submissions.find(s=>s.assignment_id===assignment.id&&s.student_id===studentId);
 const [tab,setTab]=useState<'Submission'|'Feedback'|'History'>('Submission'),[feedback,setFeedback]=useState(submission?.feedback||''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const student=assignedStudents(ctx,assignment).find(s=>s.id===studentId);
 const [files,setFiles]=useState<StoredFile[]>([]);
 useEffect(()=>{if(!submission)return;void supabase.from('assignment_submission_files').select('id,storage_path,file_name,mime_type,file_size').eq('submission_id',submission.id).then(r=>{if(!r.error)setFiles((r.data||[]) as StoredFile[])})},[submission]);
 if(!student)return <ErrorState message="This student is not assigned to this assignment." retry={back}/>;
 const late=submission?new Date(submission.submitted_at)>new Date(assignment.due_at):false,status=submission?(late?'Late':'Submitted'):(new Date(assignment.due_at)<new Date()?'Not Submitted':'Pending');
 async function download(file:StoredFile){const result=await supabase.storage.from('assignment-files').createSignedUrl(file.storage_path,90,{download:file.file_name});if(result.error)setError(result.error.message);else location.assign(result.data.signedUrl)}
 async function save(){if(!submission)return;setSaving(true);const result=await supabase.from('assignment_submissions').update({feedback:feedback.trim()||null,feedback_updated_at:new Date().toISOString(),feedback_by:ctx.userId,updated_at:new Date().toISOString()}).eq('id',submission.id);setSaving(false);if(result.error)setError(result.error.message);else await refresh()}
 return <div className="mx-auto max-w-3xl space-y-4"><Header back={back} title={student.name}/><section className="flex items-center gap-4 rounded-2xl bg-gradient-to-br from-blue-50 to-sky-100 p-4 dark:from-blue-950 dark:to-slate-900"><span className="grid h-20 w-20 place-items-center rounded-full bg-blue-200 text-3xl font-bold text-blue-700">{student.name[0]}</span><div><h1 className="text-xl font-extrabold">{student.name}</h1><p className="text-sm">{classLabel(ctx.classes.find(c=>c.id===assignment.class_id))} · Roll No. {student.roll_no||'—'}</p><div className="mt-2"><Badge status={status}/></div></div></section><Tabs values={['Submission','Feedback','History']} active={tab} set={v=>setTab(v as typeof tab)}/>
 {tab==='Submission'&&<><section className={`${card} p-4`}><h2 className="font-bold">Submission Details</h2><div className="mt-3 divide-y text-sm dark:divide-slate-800"><Row label="Submitted On" value={submission?dueLabel(submission.submitted_at):'Not submitted'}/><Row label="Submitted Late" value={submission?(late?'Yes':'No'):'—'}/><Row label="Files Submitted" value={`${files.length} file${files.length===1?'':'s'}`}/><Row label="Student Note" value={submission?.student_note||'—'}/></div></section><section className={`${card} p-4`}><h2 className="font-bold">Submitted Files</h2>{files.length?files.map(f=><button key={f.id} onClick={()=>download(f)} className="mt-2 flex w-full items-center gap-3 rounded-xl bg-slate-50 p-3 text-left dark:bg-slate-900"><FileText className="text-blue-600"/><div className="min-w-0 flex-1"><b className="block truncate text-sm">{f.file_name}</b><span className="text-xs text-slate-500">{formatBytes(f.file_size)}</span></div><Download className="h-4 w-4 text-blue-600"/></button>):<p className="mt-3 text-sm text-slate-500">No submitted files.</p>}</section></>}
 {tab==='Feedback'&&<section className={`${card} p-4`}><h2 className="font-bold">Teacher Feedback</h2>{submission?<><textarea value={feedback} onChange={e=>setFeedback(e.target.value.slice(0,3000))} rows={6} className={` mt-3`} placeholder="Write constructive feedback…"/><p className="mt-2 text-xs text-slate-500">{submission.feedback_updated_at?`Last updated ${dueLabel(submission.feedback_updated_at)}`:'No feedback saved yet.'}</p><button onClick={save} disabled={saving} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 font-semibold text-white"><MessageSquare className="h-4 w-4"/>{saving?'Saving…':'Save Feedback'}</button></>:<p className="mt-3 text-sm text-slate-500">Feedback becomes available after the student submits.</p>}{error&&<p className="mt-2 text-sm text-red-600">{error}</p>}</section>}
 {tab==='History'&&<section className={`${card} p-4`}><h2 className="font-bold">History</h2><div className="mt-3 space-y-3 text-sm">{submission?<><p><CheckCircle2 className="mr-2 inline h-4 w-4 text-emerald-600"/>Submitted {dueLabel(submission.submitted_at)}</p>{submission.feedback_updated_at&&<p><MessageSquare className="mr-2 inline h-4 w-4 text-blue-600"/>Feedback updated {dueLabel(submission.feedback_updated_at)}</p>}</>:<p className="text-slate-500">No submission history yet.</p>}</div></section>}</div>
}

function assignedStudents(ctx:Context,a:Assignment){const cls=ctx.classes.find(c=>c.id===a.class_id);if(!cls)return[];const list=ctx.students.filter(s=>belongs(s,cls));if(a.target_mode==='class')return list;const targets=new Set(ctx.targets.filter(t=>t.assignment_id===a.id).map(t=>t.student_id));return list.filter(s=>targets.has(s.id))}
function Header({back,title}:{back:()=>void;title:string}){return <div className="flex items-center gap-3"><button onClick={back} aria-label="Go back"><ArrowLeft/></button><h1 className="truncate text-xl font-bold">{title}</h1></div>}
function Tabs({values,active,set}:{values:string[];active:string;set:(value:string)=>void}){return <div className="grid border-b dark:border-slate-800" style={{gridTemplateColumns:`repeat(${values.length},minmax(0,1fr))`}}>{values.map(v=><button key={v} onClick={()=>set(v)} className={`border-b-2 py-3 text-sm ${active===v?'border-blue-600 font-semibold text-blue-600':'border-transparent text-slate-500'}`}>{v}</button>)}</div>}
function Stat({icon:Icon,value,label,tone}:{icon:typeof FileText;value:number;label:string;tone:'blue'|'green'|'amber'|'rose'}){const c={blue:'bg-blue-50 text-blue-600',green:'bg-emerald-50 text-emerald-600',amber:'bg-amber-50 text-amber-600',rose:'bg-rose-50 text-rose-600'};return <div className={`rounded-2xl p-3 text-center dark:bg-slate-900 ${c[tone]}`}><Icon className="mx-auto h-5 w-5"/><b className="mt-1 block text-xl text-slate-950 dark:text-white">{value}</b><span className="text-[11px] text-slate-600 dark:text-slate-300">{label}</span></div>}
function Badge({status}:{status:string}){const c=status==='Active'||status==='Submitted'||status==='Completed'?'bg-emerald-100 text-emerald-700':status==='Pending'?'bg-amber-100 text-amber-700':status==='Late'?'bg-orange-100 text-orange-700':'bg-rose-100 text-rose-700';return <span className={`whitespace-nowrap rounded-full px-2 py-1 text-[10px] font-semibold ${c}`}>{status}</span>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1 block text-xs text-slate-500">{label}</span>{children}</label>}
function Row({label,value}:{label:string;value:string}){return <div className="grid grid-cols-[130px_1fr] gap-3 py-3"><span className="text-slate-500">{label}</span><span>{value}</span></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-900"><b className="text-2xl text-blue-600">{value}</b><p className="text-xs text-slate-500">{label}</p></div>}
function Empty({title,body}:{title:string;body:string}){return <div className={`${card} p-10 text-center`}><FileText className="mx-auto h-8 w-8 text-slate-400"/><b className="mt-3 block">{title}</b><p className="mt-1 text-sm text-slate-500">{body}</p></div>}
function ErrorState({message,retry}:{message:string;retry:()=>void|Promise<void>}){return <div className={`${card} mx-auto max-w-lg p-6 text-center`}><b>Assignments unavailable</b><p className="mt-2 text-sm text-slate-500">{message}</p><button onClick={()=>void retry()} className="mt-4 rounded-xl bg-blue-600 px-4 py-2 text-white">Try again</button></div>}
function Shell({children}:{children:React.ReactNode}){return <div className="min-h-screen bg-slate-50 text-slate-950 dark:bg-slate-950 dark:text-white"><Sidebar/><div className="min-h-screen pt-10 lg:ml-64"><TopBar/><main className="px-4 pb-24 pt-24 sm:px-6 lg:px-8">{children}</main></div></div>}
