'use client';

import {useEffect,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import Link from 'next/link';
import {ArrowLeft,BookOpen,CalendarDays,Clock3,MapPin,Save,Users} from 'lucide-react';
import Sidebar from '@/components/sidebar';
import TopBar from '@/components/TopBar';
import {supabase} from '@/lib/supabase';
import {formatTime,isoDate,type Period} from '@/lib/teacher-timetable';

type Detail={schoolId:string;teacherId:string;userId:string;assignmentId:string;classId:string;className:string;subject:string;period:Period;students:{id:string;name:string;roll_no:string|null;status?:string}[];note:string};
type ClassRow={class_name:string|null;class:string|null;name:string|null;class_number:string|null;section:string|null;section_name:string|null};
type AttendanceRow={student_id:string;status:string};
type StudentRow={id:string;name:string;roll_no:string|null;class:string|null;section:string|null};
const normalize=(value:string|null|undefined)=>String(value||'').trim().toLowerCase().replace(/^(class|grade)\s+/,'');

export default function PeriodDetails({assignmentId}:{assignmentId:string}) {
 const router=useRouter(),search=useSearchParams();
 const date=search.get('date')||isoDate(new Date());
 const [detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[note,setNote]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{let active=true;(async()=>{try{const {data:auth}=await supabase.auth.getUser();if(!auth.user)throw Error('Please sign in.');const {data:profile}=await supabase.from('profiles').select('school_id,role').eq('user_id',auth.user.id).single();if(profile?.role!=='teacher')throw Error('Teacher access required.');const {data:teacher}=await supabase.from('teachers').select('id').eq('school_id',profile.school_id).eq('user_id',auth.user.id).is('left_at',null).single();if(!teacher)throw Error('Active teacher membership unavailable.');
 const {data:a,error:ae}=await supabase.from('teacher_assignments').select('id,class_id,class_name,subject,period_id,teacher_id,school_id,active').eq('id',assignmentId).eq('school_id',profile.school_id).eq('teacher_id',teacher.id).eq('active',true).single();if(ae||!a||!a.period_id)throw Error('This period is not assigned to you.');
 const [pr,cr,sr,ar,nr]=await Promise.all([
  supabase.from('school_periods').select('id,name,kind,position,start_time,end_time,academic_year').eq('id',a.period_id).eq('school_id',profile.school_id).single(),
  supabase.from('classes').select('class_name,class,name,class_number,section,section_name').eq('id',a.class_id).eq('school_id',profile.school_id).single(),
  supabase.from('students').select('id,name,roll_no,class,section').eq('school_id',profile.school_id).order('roll_no'),
  supabase.from('attendance').select('student_id,status').eq('school_id',profile.school_id).eq('attendance_date',date),
  supabase.from('teacher_period_notes').select('content').eq('assignment_id',assignmentId).eq('note_date',date).maybeSingle(),
 ]);if(pr.error||cr.error||sr.error||ar.error)throw(pr.error||cr.error||sr.error||ar.error);
 const c=cr.data as ClassRow;const grade=normalize(c.class_name||c.class||c.name||c.class_number),section=normalize(c.section_name||c.section);const attendance=new Map(((ar.data||[]) as AttendanceRow[]).map(row=>[row.student_id,row.status]));
 const students=((sr.data||[]) as StudentRow[]).filter(student=>normalize(student.class)===grade&&normalize(student.section)===section).map(student=>({id:student.id,name:student.name,roll_no:student.roll_no,status:attendance.get(student.id)}));
 const value={schoolId:profile.school_id,teacherId:teacher.id,userId:auth.user.id,assignmentId:a.id,classId:a.class_id,className:[c.class_name||c.class||c.name||c.class_number,c.section_name||c.section].filter(Boolean).join(' '),subject:a.subject,period:pr.data as Period,students,note:nr.data?.content||''};if(active){setDetail(value);setNote(value.note)}}catch(reason){if(active)setError(reason instanceof Error?reason.message:'Could not load period.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[assignmentId,date]);
 async function save(){if(!detail||!note.trim())return;setSaving(true);setError('');setSaved(false);const {error:saveError}=await supabase.from('teacher_period_notes').upsert({school_id:detail.schoolId,teacher_id:detail.teacherId,assignment_id:detail.assignmentId,note_date:date,content:note.trim(),created_by:detail.userId,updated_at:new Date().toISOString()},{onConflict:'assignment_id,note_date'});setSaving(false);if(saveError){setError(saveError.message);return}setSaved(true)}
 if(loading)return <Shell><div className="mx-auto h-96 max-w-3xl animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-800"/></Shell>;
 if(error&&!detail)return <Shell><div className="mx-auto max-w-lg rounded-2xl border p-6 text-center dark:border-slate-800"><b>Period unavailable</b><p className="mt-2 text-sm text-slate-500">{error}</p><button onClick={()=>router.back()} className="mt-4 rounded-xl bg-blue-600 px-4 py-2 text-white">Go back</button></div></Shell>;
 if(!detail)return null;const duration=Math.max(0,(Number(detail.period.end_time.slice(0,2))*60+Number(detail.period.end_time.slice(3,5)))-(Number(detail.period.start_time.slice(0,2))*60+Number(detail.period.start_time.slice(3,5))));
 return <Shell><div className="mx-auto max-w-3xl space-y-4 text-slate-950 dark:text-white"><div className="flex items-center gap-3"><button onClick={()=>router.back()} aria-label="Back"><ArrowLeft/></button><h1 className="text-xl font-bold">Class Period Details</h1></div>
 <section className="rounded-2xl bg-gradient-to-br from-blue-50 to-sky-100 p-5 dark:from-blue-950 dark:to-slate-900"><div className="flex items-start gap-3"><span className="grid h-12 w-12 place-items-center rounded-xl bg-white text-blue-600 dark:bg-slate-900"><BookOpen/></span><div className="flex-1"><h2 className="text-2xl font-extrabold">{detail.className}</h2><p className="font-semibold">{detail.subject}</p></div><span className="rounded-lg bg-blue-100 px-2 py-1 text-xs font-semibold text-blue-700">Period {detail.period.position}</span></div><div className="mt-4 grid gap-2 text-sm"><p className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-blue-600"/>{new Date(`${date}T12:00:00`).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric'})}</p><p className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-blue-600"/>{formatTime(detail.period.start_time)} – {formatTime(detail.period.end_time)} ({duration} min)</p><p className="flex items-center gap-2 text-slate-500"><MapPin className="h-4 w-4"/>Room not recorded</p></div></section>
 <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950"><h3 className="font-bold">Class Information</h3><div className="mt-3 divide-y text-sm dark:divide-slate-800"><Info icon={Users} label="Class & Section" value={detail.className}/><Info icon={BookOpen} label="Subject" value={detail.subject}/><Info icon={Users} label="Total Students" value={String(detail.students.length)}/><Info icon={Users} label="My Role" value="Subject Teacher"/></div></section>
 <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950"><div className="flex items-center justify-between"><h3 className="font-bold">Students</h3><Link href={`/teacher/students/${detail.classId}`} className="text-sm font-semibold text-blue-600">View all →</Link></div>{detail.students.length?<div className="mt-4 grid grid-cols-4 gap-3">{detail.students.slice(0,4).map(student=><Link href={`/teacher/students/${detail.classId}/${student.id}`} key={student.id} className="text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-blue-100 font-bold text-blue-700">{student.name.charAt(0)}</span><b className="mt-1 block truncate text-xs">{student.name}</b>{student.status&&<span className={`mt-1 inline-block rounded-full px-2 py-0.5 text-[10px] ${student.status==='present'?'bg-emerald-100 text-emerald-700':student.status==='absent'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{student.status}</span>}</Link>)}</div>:<p className="mt-3 text-sm text-slate-500">No enrolled students found.</p>}</section>
 <section className="rounded-2xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950"><h3 className="font-bold">Period Note</h3><p className="mt-1 text-xs text-slate-500">Record lesson completion, chapter coverage, or a homework reminder.</p><textarea value={note} onChange={event=>{setNote(event.target.value.slice(0,500));setSaved(false)}} rows={3} className="mt-3 w-full rounded-xl border border-slate-200 bg-transparent p-3 text-sm outline-none focus:border-blue-500 dark:border-slate-700" placeholder="Add a short note…"/><div className="mt-2 flex items-center justify-between"><span className="text-xs text-slate-400">{note.length}/500</span><button onClick={save} disabled={saving||!note.trim()} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving…':saved?'Saved':'Save note'}</button></div>{error&&<p className="mt-2 text-sm text-red-600">{error}</p>}</section>
 </div></Shell>
}
function Info({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string}){return <div className="grid grid-cols-[24px_1fr_1fr] gap-2 py-3"><Icon className="h-4 w-4 text-slate-500"/><span className="text-slate-500">{label}</span><span>{value}</span></div>}
function Shell({children}:{children:React.ReactNode}){return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><Sidebar/><div className="min-h-screen pt-10 lg:ml-64"><TopBar/><main className="px-4 pb-24 pt-24 sm:px-6 lg:px-8">{children}</main></div></div>}
